// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: iam/authz/v4/authz.proto

package authzv4

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationMode int32

const (
	AuthorizationMode_AUTHORIZATION_MODE_UNSPECIFIED AuthorizationMode = 0
	AuthorizationMode_UNCONDITIONAL                  AuthorizationMode = 1
	// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
	AuthorizationMode_OBJECT_CHECK_REQUIRED AuthorizationMode = 2
)

// Enum value maps for AuthorizationMode.
var (
	AuthorizationMode_name = map[int32]string{
		0: "AUTHORIZATION_MODE_UNSPECIFIED",
		1: "UNCONDITIONAL",
		2: "OBJECT_CHECK_REQUIRED",
	}
	AuthorizationMode_value = map[string]int32{
		"AUTHORIZATION_MODE_UNSPECIFIED": 0,
		"UNCONDITIONAL":                  1,
		"OBJECT_CHECK_REQUIRED":          2,
	}
)

func (x AuthorizationMode) Enum() *AuthorizationMode {
	p := new(AuthorizationMode)
	*p = x
	return p
}

func (x AuthorizationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_authz_v4_authz_proto_enumTypes[0].Descriptor()
}

func (AuthorizationMode) Type() protoreflect.EnumType {
	return &file_iam_authz_v4_authz_proto_enumTypes[0]
}

func (x AuthorizationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationMode.Descriptor instead.
func (AuthorizationMode) EnumDescriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{0}
}

type DecisionReason int32

const (
	DecisionReason_DECISION_REASON_UNSPECIFIED DecisionReason = 0
	DecisionReason_ALLOWED                     DecisionReason = 1
	DecisionReason_NOT_MATCHED                 DecisionReason = 2
	// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
	DecisionReason_ATTRIBUTE_MISSING DecisionReason = 3
)

// Enum value maps for DecisionReason.
var (
	DecisionReason_name = map[int32]string{
		0: "DECISION_REASON_UNSPECIFIED",
		1: "ALLOWED",
		2: "NOT_MATCHED",
		3: "ATTRIBUTE_MISSING",
	}
	DecisionReason_value = map[string]int32{
		"DECISION_REASON_UNSPECIFIED": 0,
		"ALLOWED":                     1,
		"NOT_MATCHED":                 2,
		"ATTRIBUTE_MISSING":           3,
	}
)

func (x DecisionReason) Enum() *DecisionReason {
	p := new(DecisionReason)
	*p = x
	return p
}

func (x DecisionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_authz_v4_authz_proto_enumTypes[1].Descriptor()
}

func (DecisionReason) Type() protoreflect.EnumType {
	return &file_iam_authz_v4_authz_proto_enumTypes[1]
}

func (x DecisionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionReason.Descriptor instead.
func (DecisionReason) EnumDescriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{1}
}

// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
type ObjectAttribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*ObjectAttribute_StringValue
	//	*ObjectAttribute_Int64Value
	//	*ObjectAttribute_BoolValue
	Value         isObjectAttribute_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectAttribute) Reset() {
	*x = ObjectAttribute{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectAttribute) ProtoMessage() {}

func (x *ObjectAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectAttribute.ProtoReflect.Descriptor instead.
func (*ObjectAttribute) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectAttribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectAttribute) GetValue() isObjectAttribute_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ObjectAttribute) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*ObjectAttribute_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ObjectAttribute) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*ObjectAttribute_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *ObjectAttribute) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*ObjectAttribute_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isObjectAttribute_Value interface {
	isObjectAttribute_Value()
}

type ObjectAttribute_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ObjectAttribute_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type ObjectAttribute_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*ObjectAttribute_StringValue) isObjectAttribute_Value() {}

func (*ObjectAttribute_Int64Value) isObjectAttribute_Value() {}

func (*ObjectAttribute_BoolValue) isObjectAttribute_Value() {}

// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
type ObjectContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Attributes    []*ObjectAttribute     `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectContext) Reset() {
	*x = ObjectContext{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectContext) ProtoMessage() {}

func (x *ObjectContext) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectContext.ProtoReflect.Descriptor instead.
func (*ObjectContext) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectContext) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ObjectContext) GetAttributes() []*ObjectAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CheckRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Subject  string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Resource string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action   string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
	ObjectContext *ObjectContext `protobuf:"bytes,5,opt,name=object_context,json=objectContext,proto3" json:"object_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CheckRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
func (x *CheckRequest) GetObjectContext() *ObjectContext {
	if x != nil {
		return x.ObjectContext
	}
	return nil
}

type CheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Allowed        bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason         DecisionReason         `protobuf:"varint,2,opt,name=reason,proto3,enum=iam.authz.v4.DecisionReason" json:"reason,omitempty"`
	DenyCode       string                 `protobuf:"bytes,3,opt,name=deny_code,json=denyCode,proto3" json:"deny_code,omitempty"`
	MatchedGrantId string                 `protobuf:"bytes,4,opt,name=matched_grant_id,json=matchedGrantId,proto3" json:"matched_grant_id,omitempty"`
	MatchedRole    string                 `protobuf:"bytes,5,opt,name=matched_role,json=matchedRole,proto3" json:"matched_role,omitempty"`
	PolicyVersion  int64                  `protobuf:"varint,6,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
	MissingAttributeKeys []string `protobuf:"bytes,7,rep,name=missing_attribute_keys,json=missingAttributeKeys,proto3" json:"missing_attribute_keys,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetReason() DecisionReason {
	if x != nil {
		return x.Reason
	}
	return DecisionReason_DECISION_REASON_UNSPECIFIED
}

func (x *CheckResponse) GetDenyCode() string {
	if x != nil {
		return x.DenyCode
	}
	return ""
}

func (x *CheckResponse) GetMatchedGrantId() string {
	if x != nil {
		return x.MatchedGrantId
	}
	return ""
}

func (x *CheckResponse) GetMatchedRole() string {
	if x != nil {
		return x.MatchedRole
	}
	return ""
}

func (x *CheckResponse) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

// Deprecated: Marked as deprecated in iam/authz/v4/authz.proto.
func (x *CheckResponse) GetMissingAttributeKeys() []string {
	if x != nil {
		return x.MissingAttributeKeys
	}
	return nil
}

type PermissionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Mode          AuthorizationMode      `protobuf:"varint,3,opt,name=mode,proto3,enum=iam.authz.v4.AuthorizationMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionEntry) Reset() {
	*x = PermissionEntry{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionEntry) ProtoMessage() {}

func (x *PermissionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionEntry.ProtoReflect.Descriptor instead.
func (*PermissionEntry) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{4}
}

func (x *PermissionEntry) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionEntry) GetMode() AuthorizationMode {
	if x != nil {
		return x.Mode
	}
	return AuthorizationMode_AUTHORIZATION_MODE_UNSPECIFIED
}

type GetAuthorizationSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	AppName       string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorizationSnapshotRequest) Reset() {
	*x = GetAuthorizationSnapshotRequest{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizationSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationSnapshotRequest) ProtoMessage() {}

func (x *GetAuthorizationSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorizationSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuthorizationSnapshotRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetAuthorizationSnapshotRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type GetAuthorizationSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roles contains the directly assigned roles for app_name, identical to direct_roles.
	Roles         []string           `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []*PermissionEntry `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	PolicyVersion int64              `protobuf:"varint,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// direct_roles contains only assignments directly bound to the subject.
	DirectRoles   []string `protobuf:"bytes,4,rep,name=direct_roles,json=directRoles,proto3" json:"direct_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorizationSnapshotResponse) Reset() {
	*x = GetAuthorizationSnapshotResponse{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizationSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationSnapshotResponse) ProtoMessage() {}

func (x *GetAuthorizationSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorizationSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuthorizationSnapshotResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetAuthorizationSnapshotResponse) GetPermissions() []*PermissionEntry {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetAuthorizationSnapshotResponse) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *GetAuthorizationSnapshotResponse) GetDirectRoles() []string {
	if x != nil {
		return x.DirectRoles
	}
	return nil
}

type GrantAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	GrantedBy     string                 `protobuf:"bytes,4,opt,name=granted_by,json=grantedBy,proto3" json:"granted_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAssignmentRequest) Reset() {
	*x = GrantAssignmentRequest{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAssignmentRequest) ProtoMessage() {}

func (x *GrantAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAssignmentRequest.ProtoReflect.Descriptor instead.
func (*GrantAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{7}
}

func (x *GrantAssignmentRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GrantAssignmentRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *GrantAssignmentRequest) GetGrantedBy() string {
	if x != nil {
		return x.GrantedBy
	}
	return ""
}

type GrantAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyVersion int64                  `protobuf:"varint,1,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAssignmentResponse) Reset() {
	*x = GrantAssignmentResponse{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAssignmentResponse) ProtoMessage() {}

func (x *GrantAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAssignmentResponse.ProtoReflect.Descriptor instead.
func (*GrantAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{8}
}

func (x *GrantAssignmentResponse) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

type RevokeAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RevokedBy     string                 `protobuf:"bytes,4,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAssignmentRequest) Reset() {
	*x = RevokeAssignmentRequest{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAssignmentRequest) ProtoMessage() {}

func (x *RevokeAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAssignmentRequest.ProtoReflect.Descriptor instead.
func (*RevokeAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeAssignmentRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RevokeAssignmentRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RevokeAssignmentRequest) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *RevokeAssignmentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyVersion int64                  `protobuf:"varint,1,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAssignmentResponse) Reset() {
	*x = RevokeAssignmentResponse{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAssignmentResponse) ProtoMessage() {}

func (x *RevokeAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAssignmentResponse.ProtoReflect.Descriptor instead.
func (*RevokeAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeAssignmentResponse) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

type ReplaceManagedAssignmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	RoleNames     []string               `protobuf:"bytes,3,rep,name=role_names,json=roleNames,proto3" json:"role_names,omitempty"`
	ChangedBy     string                 `protobuf:"bytes,4,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceManagedAssignmentsRequest) Reset() {
	*x = ReplaceManagedAssignmentsRequest{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceManagedAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceManagedAssignmentsRequest) ProtoMessage() {}

func (x *ReplaceManagedAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceManagedAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*ReplaceManagedAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{11}
}

func (x *ReplaceManagedAssignmentsRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ReplaceManagedAssignmentsRequest) GetRoleNames() []string {
	if x != nil {
		return x.RoleNames
	}
	return nil
}

func (x *ReplaceManagedAssignmentsRequest) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *ReplaceManagedAssignmentsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReplaceManagedAssignmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectRoles   []string               `protobuf:"bytes,1,rep,name=direct_roles,json=directRoles,proto3" json:"direct_roles,omitempty"`
	PolicyVersion int64                  `protobuf:"varint,2,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	Changed       bool                   `protobuf:"varint,3,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceManagedAssignmentsResponse) Reset() {
	*x = ReplaceManagedAssignmentsResponse{}
	mi := &file_iam_authz_v4_authz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceManagedAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceManagedAssignmentsResponse) ProtoMessage() {}

func (x *ReplaceManagedAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v4_authz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceManagedAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*ReplaceManagedAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_iam_authz_v4_authz_proto_rawDescGZIP(), []int{12}
}

func (x *ReplaceManagedAssignmentsResponse) GetDirectRoles() []string {
	if x != nil {
		return x.DirectRoles
	}
	return nil
}

func (x *ReplaceManagedAssignmentsResponse) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *ReplaceManagedAssignmentsResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

var File_iam_authz_v4_authz_proto protoreflect.FileDescriptor

const file_iam_authz_v4_authz_proto_rawDesc = "" +
	"\n" +
	"\x18iam/authz/v4/authz.proto\x12\fiam.authz.v4\"\x99\x01\n" +
	"\x0fObjectAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\x03 \x01(\x03H\x00R\n" +
	"int64Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue:\x02\x18\x01B\a\n" +
	"\x05value\"o\n" +
	"\rObjectContext\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12=\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2\x1d.iam.authz.v4.ObjectAttributeR\n" +
	"attributes:\x02\x18\x01\"\xb2\x01\n" +
	"\fCheckRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12F\n" +
	"\x0eobject_context\x18\x05 \x01(\v2\x1b.iam.authz.v4.ObjectContextB\x02\x18\x01R\robjectContextJ\x04\b\x02\x10\x03R\x06domain\"\xaa\x02\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x124\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1c.iam.authz.v4.DecisionReasonR\x06reason\x12\x1b\n" +
	"\tdeny_code\x18\x03 \x01(\tR\bdenyCode\x12(\n" +
	"\x10matched_grant_id\x18\x04 \x01(\tR\x0ematchedGrantId\x12!\n" +
	"\fmatched_role\x18\x05 \x01(\tR\vmatchedRole\x12%\n" +
	"\x0epolicy_version\x18\x06 \x01(\x03R\rpolicyVersion\x128\n" +
	"\x16missing_attribute_keys\x18\a \x03(\tB\x02\x18\x01R\x14missingAttributeKeys\"z\n" +
	"\x0fPermissionEntry\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x123\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1f.iam.authz.v4.AuthorizationModeR\x04mode\"d\n" +
	"\x1fGetAuthorizationSnapshotRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappNameJ\x04\b\x02\x10\x03R\x06domain\"\xc3\x01\n" +
	" GetAuthorizationSnapshotResponse\x12\x14\n" +
	"\x05roles\x18\x01 \x03(\tR\x05roles\x12?\n" +
	"\vpermissions\x18\x02 \x03(\v2\x1d.iam.authz.v4.PermissionEntryR\vpermissions\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\x03R\rpolicyVersion\x12!\n" +
	"\fdirect_roles\x18\x04 \x03(\tR\vdirectRoles\"|\n" +
	"\x16GrantAssignmentRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\x12\x1d\n" +
	"\n" +
	"granted_by\x18\x04 \x01(\tR\tgrantedByJ\x04\b\x02\x10\x03R\x06domain\"@\n" +
	"\x17GrantAssignmentResponse\x12%\n" +
	"\x0epolicy_version\x18\x01 \x01(\x03R\rpolicyVersion\"\x95\x01\n" +
	"\x17RevokeAssignmentRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x04 \x01(\tR\trevokedBy\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reasonJ\x04\b\x02\x10\x03R\x06domain\"A\n" +
	"\x18RevokeAssignmentResponse\x12%\n" +
	"\x0epolicy_version\x18\x01 \x01(\x03R\rpolicyVersion\"\xa0\x01\n" +
	" ReplaceManagedAssignmentsRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"role_names\x18\x03 \x03(\tR\troleNames\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x04 \x01(\tR\tchangedBy\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reasonJ\x04\b\x02\x10\x03R\x06domain\"\x87\x01\n" +
	"!ReplaceManagedAssignmentsResponse\x12!\n" +
	"\fdirect_roles\x18\x01 \x03(\tR\vdirectRoles\x12%\n" +
	"\x0epolicy_version\x18\x02 \x01(\x03R\rpolicyVersion\x12\x18\n" +
	"\achanged\x18\x03 \x01(\bR\achanged*i\n" +
	"\x11AuthorizationMode\x12\"\n" +
	"\x1eAUTHORIZATION_MODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rUNCONDITIONAL\x10\x01\x12\x1d\n" +
	"\x15OBJECT_CHECK_REQUIRED\x10\x02\x1a\x02\b\x01*j\n" +
	"\x0eDecisionReason\x12\x1f\n" +
	"\x1bDECISION_REASON_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aALLOWED\x10\x01\x12\x0f\n" +
	"\vNOT_MATCHED\x10\x02\x12\x19\n" +
	"\x11ATTRIBUTE_MISSING\x10\x03\x1a\x02\b\x012\x94\x04\n" +
	"\x14AuthorizationService\x12@\n" +
	"\x05Check\x12\x1a.iam.authz.v4.CheckRequest\x1a\x1b.iam.authz.v4.CheckResponse\x12y\n" +
	"\x18GetAuthorizationSnapshot\x12-.iam.authz.v4.GetAuthorizationSnapshotRequest\x1a..iam.authz.v4.GetAuthorizationSnapshotResponse\x12^\n" +
	"\x0fGrantAssignment\x12$.iam.authz.v4.GrantAssignmentRequest\x1a%.iam.authz.v4.GrantAssignmentResponse\x12a\n" +
	"\x10RevokeAssignment\x12%.iam.authz.v4.RevokeAssignmentRequest\x1a&.iam.authz.v4.RevokeAssignmentResponse\x12|\n" +
	"\x19ReplaceManagedAssignments\x12..iam.authz.v4.ReplaceManagedAssignmentsRequest\x1a/.iam.authz.v4.ReplaceManagedAssignmentsResponseB>Z<github.com/FangcunMount/iam/v5/api/grpc/iam/authz/v4;authzv4b\x06proto3"

var (
	file_iam_authz_v4_authz_proto_rawDescOnce sync.Once
	file_iam_authz_v4_authz_proto_rawDescData []byte
)

func file_iam_authz_v4_authz_proto_rawDescGZIP() []byte {
	file_iam_authz_v4_authz_proto_rawDescOnce.Do(func() {
		file_iam_authz_v4_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_authz_v4_authz_proto_rawDesc), len(file_iam_authz_v4_authz_proto_rawDesc)))
	})
	return file_iam_authz_v4_authz_proto_rawDescData
}

var file_iam_authz_v4_authz_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_iam_authz_v4_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_iam_authz_v4_authz_proto_goTypes = []any{
	(AuthorizationMode)(0),                    // 0: iam.authz.v4.AuthorizationMode
	(DecisionReason)(0),                       // 1: iam.authz.v4.DecisionReason
	(*ObjectAttribute)(nil),                   // 2: iam.authz.v4.ObjectAttribute
	(*ObjectContext)(nil),                     // 3: iam.authz.v4.ObjectContext
	(*CheckRequest)(nil),                      // 4: iam.authz.v4.CheckRequest
	(*CheckResponse)(nil),                     // 5: iam.authz.v4.CheckResponse
	(*PermissionEntry)(nil),                   // 6: iam.authz.v4.PermissionEntry
	(*GetAuthorizationSnapshotRequest)(nil),   // 7: iam.authz.v4.GetAuthorizationSnapshotRequest
	(*GetAuthorizationSnapshotResponse)(nil),  // 8: iam.authz.v4.GetAuthorizationSnapshotResponse
	(*GrantAssignmentRequest)(nil),            // 9: iam.authz.v4.GrantAssignmentRequest
	(*GrantAssignmentResponse)(nil),           // 10: iam.authz.v4.GrantAssignmentResponse
	(*RevokeAssignmentRequest)(nil),           // 11: iam.authz.v4.RevokeAssignmentRequest
	(*RevokeAssignmentResponse)(nil),          // 12: iam.authz.v4.RevokeAssignmentResponse
	(*ReplaceManagedAssignmentsRequest)(nil),  // 13: iam.authz.v4.ReplaceManagedAssignmentsRequest
	(*ReplaceManagedAssignmentsResponse)(nil), // 14: iam.authz.v4.ReplaceManagedAssignmentsResponse
}
var file_iam_authz_v4_authz_proto_depIdxs = []int32{
	2,  // 0: iam.authz.v4.ObjectContext.attributes:type_name -> iam.authz.v4.ObjectAttribute
	3,  // 1: iam.authz.v4.CheckRequest.object_context:type_name -> iam.authz.v4.ObjectContext
	1,  // 2: iam.authz.v4.CheckResponse.reason:type_name -> iam.authz.v4.DecisionReason
	0,  // 3: iam.authz.v4.PermissionEntry.mode:type_name -> iam.authz.v4.AuthorizationMode
	6,  // 4: iam.authz.v4.GetAuthorizationSnapshotResponse.permissions:type_name -> iam.authz.v4.PermissionEntry
	4,  // 5: iam.authz.v4.AuthorizationService.Check:input_type -> iam.authz.v4.CheckRequest
	7,  // 6: iam.authz.v4.AuthorizationService.GetAuthorizationSnapshot:input_type -> iam.authz.v4.GetAuthorizationSnapshotRequest
	9,  // 7: iam.authz.v4.AuthorizationService.GrantAssignment:input_type -> iam.authz.v4.GrantAssignmentRequest
	11, // 8: iam.authz.v4.AuthorizationService.RevokeAssignment:input_type -> iam.authz.v4.RevokeAssignmentRequest
	13, // 9: iam.authz.v4.AuthorizationService.ReplaceManagedAssignments:input_type -> iam.authz.v4.ReplaceManagedAssignmentsRequest
	5,  // 10: iam.authz.v4.AuthorizationService.Check:output_type -> iam.authz.v4.CheckResponse
	8,  // 11: iam.authz.v4.AuthorizationService.GetAuthorizationSnapshot:output_type -> iam.authz.v4.GetAuthorizationSnapshotResponse
	10, // 12: iam.authz.v4.AuthorizationService.GrantAssignment:output_type -> iam.authz.v4.GrantAssignmentResponse
	12, // 13: iam.authz.v4.AuthorizationService.RevokeAssignment:output_type -> iam.authz.v4.RevokeAssignmentResponse
	14, // 14: iam.authz.v4.AuthorizationService.ReplaceManagedAssignments:output_type -> iam.authz.v4.ReplaceManagedAssignmentsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_iam_authz_v4_authz_proto_init() }
func file_iam_authz_v4_authz_proto_init() {
	if File_iam_authz_v4_authz_proto != nil {
		return
	}
	file_iam_authz_v4_authz_proto_msgTypes[0].OneofWrappers = []any{
		(*ObjectAttribute_StringValue)(nil),
		(*ObjectAttribute_Int64Value)(nil),
		(*ObjectAttribute_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_authz_v4_authz_proto_rawDesc), len(file_iam_authz_v4_authz_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_authz_v4_authz_proto_goTypes,
		DependencyIndexes: file_iam_authz_v4_authz_proto_depIdxs,
		EnumInfos:         file_iam_authz_v4_authz_proto_enumTypes,
		MessageInfos:      file_iam_authz_v4_authz_proto_msgTypes,
	}.Build()
	File_iam_authz_v4_authz_proto = out.File
	file_iam_authz_v4_authz_proto_goTypes = nil
	file_iam_authz_v4_authz_proto_depIdxs = nil
}
