// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: identity/v1/identity.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "active"|"inactive"|"blocked"
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Child struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LegalName string                 `protobuf:"bytes,2,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	Gender    int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Dob       string                 `protobuf:"bytes,4,opt,name=dob,proto3" json:"dob,omitempty"` // date (YYYY-MM-DD)
	IdType    string                 `protobuf:"bytes,5,opt,name=id_type,json=idType,proto3" json:"id_type,omitempty"`
	// 不返回身份证明文；若需要掩码，请服务端渲染成另一个字段
	HeightCm      int32                  `protobuf:"varint,6,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	WeightKg      string                 `protobuf:"bytes,7,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Child) Reset() {
	*x = Child{}
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Child) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Child) ProtoMessage() {}

func (x *Child) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Child.ProtoReflect.Descriptor instead.
func (*Child) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *Child) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Child) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *Child) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *Child) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *Child) GetIdType() string {
	if x != nil {
		return x.IdType
	}
	return ""
}

func (x *Child) GetHeightCm() int32 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

func (x *Child) GetWeightKg() string {
	if x != nil {
		return x.WeightKg
	}
	return ""
}

func (x *Child) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Child) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Guardianship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChildId       string                 `protobuf:"bytes,3,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	Relation      string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"` // "self"|"parent"|"guardian"
	Since         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=since,proto3" json:"since,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guardianship) Reset() {
	*x = Guardianship{}
	mi := &file_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guardianship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guardianship) ProtoMessage() {}

func (x *Guardianship) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guardianship.ProtoReflect.Descriptor instead.
func (*Guardianship) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *Guardianship) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Guardianship) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Guardianship) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

func (x *Guardianship) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Guardianship) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *Guardianship) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

// ******* 查询 *******
type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetChildReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChildId       string                 `protobuf:"bytes,1,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChildReq) Reset() {
	*x = GetChildReq{}
	mi := &file_identity_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChildReq) ProtoMessage() {}

func (x *GetChildReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChildReq.ProtoReflect.Descriptor instead.
func (*GetChildReq) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetChildReq) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

type GetUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResp) Reset() {
	*x = GetUserResp{}
	mi := &file_identity_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResp) ProtoMessage() {}

func (x *GetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResp.ProtoReflect.Descriptor instead.
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetChildResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Child         *Child                 `protobuf:"bytes,1,opt,name=child,proto3" json:"child,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChildResp) Reset() {
	*x = GetChildResp{}
	mi := &file_identity_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChildResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChildResp) ProtoMessage() {}

func (x *GetChildResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChildResp.ProtoReflect.Descriptor instead.
func (*GetChildResp) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *GetChildResp) GetChild() *Child {
	if x != nil {
		return x.Child
	}
	return nil
}

// ******* 监护判定 *******
type IsGuardianReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChildId       string                 `protobuf:"bytes,2,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsGuardianReq) Reset() {
	*x = IsGuardianReq{}
	mi := &file_identity_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsGuardianReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsGuardianReq) ProtoMessage() {}

func (x *IsGuardianReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsGuardianReq.ProtoReflect.Descriptor instead.
func (*IsGuardianReq) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *IsGuardianReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IsGuardianReq) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

type IsGuardianResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsGuardian    bool                   `protobuf:"varint,1,opt,name=is_guardian,json=isGuardian,proto3" json:"is_guardian,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsGuardianResp) Reset() {
	*x = IsGuardianResp{}
	mi := &file_identity_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsGuardianResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsGuardianResp) ProtoMessage() {}

func (x *IsGuardianResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsGuardianResp.ProtoReflect.Descriptor instead.
func (*IsGuardianResp) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *IsGuardianResp) GetIsGuardian() bool {
	if x != nil {
		return x.IsGuardian
	}
	return false
}

type ListChildrenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // default 20
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // default 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildrenReq) Reset() {
	*x = ListChildrenReq{}
	mi := &file_identity_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildrenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildrenReq) ProtoMessage() {}

func (x *ListChildrenReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildrenReq.ProtoReflect.Descriptor instead.
func (*ListChildrenReq) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{9}
}

func (x *ListChildrenReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListChildrenReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListChildrenReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListChildrenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*Child               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildrenResp) Reset() {
	*x = ListChildrenResp{}
	mi := &file_identity_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildrenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildrenResp) ProtoMessage() {}

func (x *ListChildrenResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildrenResp.ProtoReflect.Descriptor instead.
func (*ListChildrenResp) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{10}
}

func (x *ListChildrenResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListChildrenResp) GetItems() []*Child {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_identity_v1_identity_proto protoreflect.FileDescriptor

const file_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x1aidentity/v1/identity.proto\x12\x0fiam.identity.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa9\x02\n" +
	"\x05Child\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x02 \x01(\tR\tlegalName\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\x12\x10\n" +
	"\x03dob\x18\x04 \x01(\tR\x03dob\x12\x17\n" +
	"\aid_type\x18\x05 \x01(\tR\x06idType\x12\x1b\n" +
	"\theight_cm\x18\x06 \x01(\x05R\bheightCm\x12\x1b\n" +
	"\tweight_kg\x18\a \x01(\tR\bweightKg\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdb\x01\n" +
	"\fGuardianship\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bchild_id\x18\x03 \x01(\tR\achildId\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\x120\n" +
	"\x05since\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x129\n" +
	"\n" +
	"revoked_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"%\n" +
	"\n" +
	"GetUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"(\n" +
	"\vGetChildReq\x12\x19\n" +
	"\bchild_id\x18\x01 \x01(\tR\achildId\"8\n" +
	"\vGetUserResp\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.iam.identity.v1.UserR\x04user\"<\n" +
	"\fGetChildResp\x12,\n" +
	"\x05child\x18\x01 \x01(\v2\x16.iam.identity.v1.ChildR\x05child\"C\n" +
	"\rIsGuardianReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bchild_id\x18\x02 \x01(\tR\achildId\"1\n" +
	"\x0eIsGuardianResp\x12\x1f\n" +
	"\vis_guardian\x18\x01 \x01(\bR\n" +
	"isGuardian\"X\n" +
	"\x0fListChildrenReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"V\n" +
	"\x10ListChildrenResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.iam.identity.v1.ChildR\x05items2\x9d\x01\n" +
	"\fIdentityRead\x12D\n" +
	"\aGetUser\x12\x1b.iam.identity.v1.GetUserReq\x1a\x1c.iam.identity.v1.GetUserResp\x12G\n" +
	"\bGetChild\x12\x1c.iam.identity.v1.GetChildReq\x1a\x1d.iam.identity.v1.GetChildResp2\xb7\x01\n" +
	"\x11GuardianshipQuery\x12M\n" +
	"\n" +
	"IsGuardian\x12\x1e.iam.identity.v1.IsGuardianReq\x1a\x1f.iam.identity.v1.IsGuardianResp\x12S\n" +
	"\fListChildren\x12 .iam.identity.v1.ListChildrenReq\x1a!.iam.identity.v1.ListChildrenRespBLZJgithub.com/fangcun-mount/iam-contracts/api/grpc/iam/identity/v1;identityv1b\x06proto3"

var (
	file_identity_v1_identity_proto_rawDescOnce sync.Once
	file_identity_v1_identity_proto_rawDescData []byte
)

func file_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)))
	})
	return file_identity_v1_identity_proto_rawDescData
}

var file_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_identity_v1_identity_proto_goTypes = []any{
	(*User)(nil),                  // 0: iam.identity.v1.User
	(*Child)(nil),                 // 1: iam.identity.v1.Child
	(*Guardianship)(nil),          // 2: iam.identity.v1.Guardianship
	(*GetUserReq)(nil),            // 3: iam.identity.v1.GetUserReq
	(*GetChildReq)(nil),           // 4: iam.identity.v1.GetChildReq
	(*GetUserResp)(nil),           // 5: iam.identity.v1.GetUserResp
	(*GetChildResp)(nil),          // 6: iam.identity.v1.GetChildResp
	(*IsGuardianReq)(nil),         // 7: iam.identity.v1.IsGuardianReq
	(*IsGuardianResp)(nil),        // 8: iam.identity.v1.IsGuardianResp
	(*ListChildrenReq)(nil),       // 9: iam.identity.v1.ListChildrenReq
	(*ListChildrenResp)(nil),      // 10: iam.identity.v1.ListChildrenResp
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_identity_v1_identity_proto_depIdxs = []int32{
	11, // 0: iam.identity.v1.User.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: iam.identity.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: iam.identity.v1.Child.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: iam.identity.v1.Child.updated_at:type_name -> google.protobuf.Timestamp
	11, // 4: iam.identity.v1.Guardianship.since:type_name -> google.protobuf.Timestamp
	11, // 5: iam.identity.v1.Guardianship.revoked_at:type_name -> google.protobuf.Timestamp
	0,  // 6: iam.identity.v1.GetUserResp.user:type_name -> iam.identity.v1.User
	1,  // 7: iam.identity.v1.GetChildResp.child:type_name -> iam.identity.v1.Child
	1,  // 8: iam.identity.v1.ListChildrenResp.items:type_name -> iam.identity.v1.Child
	3,  // 9: iam.identity.v1.IdentityRead.GetUser:input_type -> iam.identity.v1.GetUserReq
	4,  // 10: iam.identity.v1.IdentityRead.GetChild:input_type -> iam.identity.v1.GetChildReq
	7,  // 11: iam.identity.v1.GuardianshipQuery.IsGuardian:input_type -> iam.identity.v1.IsGuardianReq
	9,  // 12: iam.identity.v1.GuardianshipQuery.ListChildren:input_type -> iam.identity.v1.ListChildrenReq
	5,  // 13: iam.identity.v1.IdentityRead.GetUser:output_type -> iam.identity.v1.GetUserResp
	6,  // 14: iam.identity.v1.IdentityRead.GetChild:output_type -> iam.identity.v1.GetChildResp
	8,  // 15: iam.identity.v1.GuardianshipQuery.IsGuardian:output_type -> iam.identity.v1.IsGuardianResp
	10, // 16: iam.identity.v1.GuardianshipQuery.ListChildren:output_type -> iam.identity.v1.ListChildrenResp
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_identity_v1_identity_proto_init() }
func file_identity_v1_identity_proto_init() {
	if File_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_identity_v1_identity_proto_depIdxs,
		MessageInfos:      file_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_identity_v1_identity_proto = out.File
	file_identity_v1_identity_proto_goTypes = nil
	file_identity_v1_identity_proto_depIdxs = nil
}
