openapi: 3.1.0
info:
  title: IAM · Identity API
  version: 1.0.0
servers:
  - url: https://api.example.com/api
    description: Production
  - url: http://localhost:8080/api
    description: Local Dev
security:
  - bearerAuth: []
tags:
  - name: Identity-Users
  - name: Identity-Children
  - name: Identity-Guardianship

paths:
  /v1/me:
    get:
      tags: [Identity-Users]
      summary: 获取当前用户信息
      operationId: GetMe
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/User' }}}}
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/InternalServerError' }
    patch:
      tags: [Identity-Users]
      summary: 更新当前用户信息
      operationId: PatchMe
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/UserUpdateReq' }
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/User' }}}}
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/InternalServerError' }

  /v1/me/children:
    get:
      tags: [Identity-Children]
      summary: 我的孩子
      operationId: ListMyChildren
      parameters: [ { $ref: '#/components/parameters/Limit' }, { $ref: '#/components/parameters/Offset' } ]
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/ChildPage' }}}}
        '401': { $ref: '#/components/responses/Unauthorized' }

  /v1/children/register:
    post:
      tags: [Identity-Children]
      summary: 注册孩子（建档+授当前用户为监护人）
      operationId: RegisterChild
      parameters: [ { $ref: '#/components/parameters/IdempotencyKey' } ]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ChildRegisterReq' }
      responses:
        '201': { description: Created, content: { application/json: { schema: { $ref: '#/components/schemas/ChildRegisterResp' }}}}
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }
        '409': { $ref: '#/components/responses/Conflict' }

  /v1/children/search:
    get:
      tags: [Identity-Children]
      summary: 查询孩子（根据姓名、性别、生日）
      operationId: SearchChildren
      parameters:
        - in: query
          name: name
          required: true
          schema: { type: string }
        - in: query
          name: gender
          schema: { type: integer }
        - in: query
          name: dob
          required: true
          schema: { type: string, format: date }
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/ChildPage' }}}}
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }

  /v1/guardians/grant:
    post:
      tags: [Identity-Guardianship]
      summary: 授予监护（为已存在的孩子添加监护人）
      operationId: GrantGuardian
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/GuardianGrantReq' }
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/Guardianship' }}}}
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }
        '409': { $ref: '#/components/responses/Conflict' }

components:
  securitySchemes:
    bearerAuth: { type: http, scheme: bearer, bearerFormat: JWT }
  parameters:
    UserId:   { in: path, name: userId, required: true, schema: { type: string } }
    ChildId:  { in: path, name: childId, required: true, schema: { type: string } }
    Limit:    { in: query, name: limit, schema: { type: integer, minimum: 1, maximum: 100, default: 20 } }
    Offset:   { in: query, name: offset, schema: { type: integer, minimum: 0, default: 0 } }
    IdempotencyKey:
      in: header
      name: X-Idempotency-Key
      schema: { type: string }
  responses:
    Unauthorized: { description: 未认证, content: { application/json: { schema: { $ref: '#/components/schemas/Error' }}}}
    Forbidden:    { description: 无权限, content: { application/json: { schema: { $ref: '#/components/schemas/Error' }}}}
    NotFound:     { description: 不存在, content: { application/json: { schema: { $ref: '#/components/schemas/Error' }}}}
    Conflict:     { description: 冲突, content: { application/json: { schema: { $ref: '#/components/schemas/Error' }}}}
    BadRequest:   { description: 参数错误, content: { application/json: { schema: { $ref: '#/components/schemas/Error' }}}}
    InternalServerError: { description: 服务器内部错误, content: { application/json: { schema: { $ref: '#/components/schemas/Error' }}}}
  schemas:
    User:
      type: object
      properties:
        id: { type: string }
        status: { type: string, enum: [active, inactive, blocked] }
        nickname: { type: string }
        avatar: { type: string, format: uri }
        contacts:
          type: array
          items: { $ref: '#/components/schemas/VerifiedContact' }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
      required: [id, status]

    UserUpdateReq:
      type: object
      properties:
        nickname: { type: string }
        avatar: { type: string, format: uri }
        contacts:
          type: array
          items: { $ref: '#/components/schemas/VerifiedContactUpsert' }

    VerifiedContact:
      type: object
      properties:
        type: { type: string, enum: [email, phone] }
        value: { type: string }
        verifiedAt: { type: string, format: date-time }

    VerifiedContactUpsert:
      type: object
      properties:
        type: { type: string, enum: [email, phone] }
        value: { type: string }

    Child:
      type: object
      properties:
        id: { type: string }
        legalName: { type: string }
        gender: { type: integer }
        dob: { type: string, format: date }
        idType: { type: string }
        idMasked: { type: string }
        heightCm: { type: integer, nullable: true }
        weightKg: { type: string, nullable: true }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
      required: [id, legalName, gender, dob, idType]

    ChildCreateReq:
      type: object
      properties:
        legalName: { type: string }
        gender: { type: integer }
        dob: { type: string, format: date }
        idType: { type: string }
        idNo: { type: string, description: '仅入参；服务端加密+哈希存储' }
        heightCm: { type: integer, nullable: true }
        weightKg: { type: string, nullable: true }
      required: [legalName, gender, dob, idType, idNo]
    ChildRegisterReq:
      allOf:
        - $ref: '#/components/schemas/ChildCreateReq'
        - type: object
          properties:
            relation:
              type: string
              enum: [self, parent, guardian]
              default: parent
    ChildRegisterResp:
      type: object
      properties:
        child: { $ref: '#/components/schemas/Child' }
        guardianship: { $ref: '#/components/schemas/Guardianship' }
    ChildPage:
      type: object
      properties:
        total: { type: integer }
        limit: { type: integer }
        offset: { type: integer }
        items:
          type: array
          items: { $ref: '#/components/schemas/Child' }

    Guardianship:
      type: object
      properties:
        id: { type: integer, format: int64 }
        userId: { type: string }
        childId: { type: string }
        relation: { type: string, enum: [self, parent, guardian] }
        since: { type: string, format: date-time }
        revokedAt: { type: string, format: date-time, nullable: true }
      required: [id, userId, childId, relation, since]
    GuardianGrantReq:
      type: object
      properties:
        userId: { type: string }
        childId: { type: string }
        relation: { type: string, enum: [self, parent, guardian] }
      required: [userId, childId, relation]

    Error:
      type: object
      properties:
        code: { type: string }
        message: { type: string }
        requestId: { type: string }

components:
  securitySchemes:
    bearerAuth: { type: http, scheme: bearer, bearerFormat: JWT }
