openapi: 3.1.0
info:
  title: IAM Identity Provider (IDP) API
  version: 1.0.0
  description: 微信应用管理及第三方身份提供能力（登录由 authn 模块统一提供）。
  contact:
    name: API Support
    email: yshujie@163.com
    url: https://github.com/FangcunMount/iam-contracts
servers:
  - url: https://iam.yangshujie.com/api/v1
    description: 生产环境
  - url: http://localhost:18081/api/v1
    description: 本地开发
tags:
  - name: IDP-WeChat
    description: 微信应用管理
  - name: Health
    description: 健康检查

paths:
  /idp/health:
    get:
      tags: [Health]
      summary: IDP 健康检查
      description: 身份提供商模块健康检查。
      operationId: IdpHealth
      responses:
        '200': { description: OK, content: { application/json: { schema: { type: object, properties: { status: { type: string }, module: { type: string }}}}}}

  /idp/wechat-apps:
    post:
      tags: [IDP-WeChat]
      summary: 创建微信应用
      description: 创建新的微信应用记录。
      operationId: CreateWechatApp
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CreateWechatAppRequest' }
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/WechatApp' }}}}

  /idp/wechat-apps/{app_id}:
    parameters: [ { in: path, name: app_id, required: true, schema: { type: string } } ]
    get:
      tags: [IDP-WeChat]
      summary: 获取微信应用
      description: 按 app_id 查询微信应用详情。
      operationId: GetWechatApp
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/WechatApp' }}}}
        '404': { $ref: '#/components/responses/NotFound' }

  /idp/wechat-apps/{app_id}/access-token:
    parameters: [ { in: path, name: app_id, required: true, schema: { type: string } } ]
    get:
      tags: [IDP-WeChat]
      summary: 获取访问令牌
      description: 获取微信应用的访问令牌。
      operationId: GetWechatAccessToken
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/AccessTokenResponse' }}}}
        '404': { $ref: '#/components/responses/NotFound' }

  /idp/wechat-apps/rotate-auth-secret:
    post:
      tags: [IDP-WeChat]
      summary: 轮换认证密钥
      description: 为微信应用轮换 AppSecret。
      operationId: RotateAuthSecret
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/RotateAuthSecretRequest' }
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/Message' }}}}

  /idp/wechat-apps/rotate-msg-secret:
    post:
      tags: [IDP-WeChat]
      summary: 轮换消息密钥
      description: 轮换微信消息加解密密钥。
      operationId: RotateMsgSecret
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/RotateMsgSecretRequest' }
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/Message' }}}}

  /idp/wechat-apps/refresh-access-token:
    post:
      tags: [IDP-WeChat]
      summary: 刷新访问令牌
      description: 刷新微信应用访问令牌。
      operationId: RefreshWechatAccessToken
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/RefreshAccessTokenRequest' }
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/AccessTokenResponse' }}}}

components:
  responses:
    NotFound: { description: 不存在, content: { application/json: { schema: { $ref: '#/components/schemas/Error' }}}}
  schemas:
    WechatApp:
      type: object
      properties:
        app_id: { type: string }
        name: { type: string }
        type: { type: string }
        app_secret: { type: string }
        status: { type: string }
        created_at: { type: string, format: date-time }

    CreateWechatAppRequest:
      type: object
      properties:
        app_id: { type: string }
        name: { type: string }
        type: { type: string }
        app_secret: { type: string }
      required: [app_id, name, type]

    RotateAuthSecretRequest:
      type: object
      properties:
        app_id: { type: string }
        new_secret: { type: string }
      required: [app_id, new_secret]

    RotateMsgSecretRequest:
      type: object
      properties:
        app_id: { type: string }
        callback_token: { type: string }
        encoding_aes_key: { type: string }
      required: [app_id, callback_token, encoding_aes_key]

    RefreshAccessTokenRequest:
      type: object
      properties:
        app_id: { type: string }
      required: [app_id]

    AccessTokenResponse:
      type: object
      properties:
        access_token: { type: string }
        expires_in: { type: integer }

    Message:
      type: object
      properties:
        message: { type: string }

    Error:
      type: object
      properties:
        code: { type: string }
        message: { type: string }
