// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: iam/authn/v2/authn.proto

package authnv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenStatus int32

const (
	TokenStatus_TOKEN_STATUS_UNSPECIFIED TokenStatus = 0
	TokenStatus_TOKEN_STATUS_VALID       TokenStatus = 1
	TokenStatus_TOKEN_STATUS_REVOKED     TokenStatus = 2
	TokenStatus_TOKEN_STATUS_EXPIRED     TokenStatus = 3
)

// Enum value maps for TokenStatus.
var (
	TokenStatus_name = map[int32]string{
		0: "TOKEN_STATUS_UNSPECIFIED",
		1: "TOKEN_STATUS_VALID",
		2: "TOKEN_STATUS_REVOKED",
		3: "TOKEN_STATUS_EXPIRED",
	}
	TokenStatus_value = map[string]int32{
		"TOKEN_STATUS_UNSPECIFIED": 0,
		"TOKEN_STATUS_VALID":       1,
		"TOKEN_STATUS_REVOKED":     2,
		"TOKEN_STATUS_EXPIRED":     3,
	}
)

func (x TokenStatus) Enum() *TokenStatus {
	p := new(TokenStatus)
	*p = x
	return p
}

func (x TokenStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_authn_v2_authn_proto_enumTypes[0].Descriptor()
}

func (TokenStatus) Type() protoreflect.EnumType {
	return &file_iam_authn_v2_authn_proto_enumTypes[0]
}

func (x TokenStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenStatus.Descriptor instead.
func (TokenStatus) EnumDescriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{0}
}

type TokenType int32

const (
	TokenType_TOKEN_TYPE_UNSPECIFIED TokenType = 0
	TokenType_TOKEN_TYPE_ACCESS      TokenType = 1
	TokenType_TOKEN_TYPE_REFRESH     TokenType = 2
)

// Enum value maps for TokenType.
var (
	TokenType_name = map[int32]string{
		0: "TOKEN_TYPE_UNSPECIFIED",
		1: "TOKEN_TYPE_ACCESS",
		2: "TOKEN_TYPE_REFRESH",
	}
	TokenType_value = map[string]int32{
		"TOKEN_TYPE_UNSPECIFIED": 0,
		"TOKEN_TYPE_ACCESS":      1,
		"TOKEN_TYPE_REFRESH":     2,
	}
)

func (x TokenType) Enum() *TokenType {
	p := new(TokenType)
	*p = x
	return p
}

func (x TokenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenType) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_authn_v2_authn_proto_enumTypes[1].Descriptor()
}

func (TokenType) Type() protoreflect.EnumType {
	return &file_iam_authn_v2_authn_proto_enumTypes[1]
}

func (x TokenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenType.Descriptor instead.
func (TokenType) EnumDescriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{1}
}

type OperatorContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    string                 `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	OperatorName  string                 `protobuf:"bytes,2,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,10,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorContext) Reset() {
	*x = OperatorContext{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorContext) ProtoMessage() {}

func (x *OperatorContext) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorContext.ProtoReflect.Descriptor instead.
func (*OperatorContext) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{0}
}

func (x *OperatorContext) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *OperatorContext) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *OperatorContext) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *OperatorContext) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OperatorContext) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type TokenClaims struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokenId         string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Subject         string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LoginIdentityId string                 `protobuf:"bytes,4,opt,name=login_identity_id,json=loginIdentityId,proto3" json:"login_identity_id,omitempty"`
	Issuer          string                 `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience        []string               `protobuf:"bytes,6,rep,name=audience,proto3" json:"audience,omitempty"`
	TenantId        string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TokenType       TokenType              `protobuf:"varint,9,opt,name=token_type,json=tokenType,proto3,enum=iam.authn.v2.TokenType" json:"token_type,omitempty"`
	IssuedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AuthenticatedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=authenticated_at,json=authenticatedAt,proto3" json:"authenticated_at,omitempty"`
	NotBefore       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	Attributes      map[string]string      `protobuf:"bytes,20,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Amr             []string               `protobuf:"bytes,21,rep,name=amr,proto3" json:"amr,omitempty"`
	OrgId           string                 `protobuf:"bytes,22,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	TenantDomain    string                 `protobuf:"bytes,23,opt,name=tenant_domain,json=tenantDomain,proto3" json:"tenant_domain,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TokenClaims) Reset() {
	*x = TokenClaims{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenClaims) ProtoMessage() {}

func (x *TokenClaims) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenClaims.ProtoReflect.Descriptor instead.
func (*TokenClaims) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{1}
}

func (x *TokenClaims) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *TokenClaims) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TokenClaims) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenClaims) GetLoginIdentityId() string {
	if x != nil {
		return x.LoginIdentityId
	}
	return ""
}

func (x *TokenClaims) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *TokenClaims) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *TokenClaims) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TokenClaims) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TokenClaims) GetTokenType() TokenType {
	if x != nil {
		return x.TokenType
	}
	return TokenType_TOKEN_TYPE_UNSPECIFIED
}

func (x *TokenClaims) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *TokenClaims) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TokenClaims) GetAuthenticatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AuthenticatedAt
	}
	return nil
}

func (x *TokenClaims) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *TokenClaims) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *TokenClaims) GetAmr() []string {
	if x != nil {
		return x.Amr
	}
	return nil
}

func (x *TokenClaims) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *TokenClaims) GetTenantDomain() string {
	if x != nil {
		return x.TenantDomain
	}
	return ""
}

type TokenPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenType     string                 `protobuf:"bytes,1,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     *durationpb.Duration   `protobuf:"bytes,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{2}
}

func (x *TokenPair) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenPair) GetExpiresIn() *durationpb.Duration {
	if x != nil {
		return x.ExpiresIn
	}
	return nil
}

type TokenMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenType     TokenType              `protobuf:"varint,1,opt,name=token_type,json=tokenType,proto3,enum=iam.authn.v2.TokenType" json:"token_type,omitempty"`
	Status        TokenStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=iam.authn.v2.TokenStatus" json:"status,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenMetadata) Reset() {
	*x = TokenMetadata{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenMetadata) ProtoMessage() {}

func (x *TokenMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenMetadata.ProtoReflect.Descriptor instead.
func (*TokenMetadata) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{3}
}

func (x *TokenMetadata) GetTokenType() TokenType {
	if x != nil {
		return x.TokenType
	}
	return TokenType_TOKEN_TYPE_UNSPECIFIED
}

func (x *TokenMetadata) GetStatus() TokenStatus {
	if x != nil {
		return x.Status
	}
	return TokenStatus_TOKEN_STATUS_UNSPECIFIED
}

func (x *TokenMetadata) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *TokenMetadata) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthMethod    string                 `protobuf:"bytes,1,opt,name=auth_method,json=authMethod,proto3" json:"auth_method,omitempty"`
	MethodPayload *structpb.Struct       `protobuf:"bytes,2,opt,name=method_payload,json=methodPayload,proto3" json:"method_payload,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetAuthMethod() string {
	if x != nil {
		return x.AuthMethod
	}
	return ""
}

func (x *LoginRequest) GetMethodPayload() *structpb.Struct {
	if x != nil {
		return x.MethodPayload
	}
	return nil
}

func (x *LoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenPair     *TokenPair             `protobuf:"bytes,1,opt,name=token_pair,json=tokenPair,proto3" json:"token_pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetTokenPair() *TokenPair {
	if x != nil {
		return x.TokenPair
	}
	return nil
}

type VerifyTokenRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessToken        string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ForceRemote        bool                   `protobuf:"varint,2,opt,name=force_remote,json=forceRemote,proto3" json:"force_remote,omitempty"`
	IncludeMetadata    bool                   `protobuf:"varint,3,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	ExpectedIssuer     string                 `protobuf:"bytes,4,opt,name=expected_issuer,json=expectedIssuer,proto3" json:"expected_issuer,omitempty"`
	ExpectedAudience   []string               `protobuf:"bytes,5,rep,name=expected_audience,json=expectedAudience,proto3" json:"expected_audience,omitempty"`
	AcceptedTokenTypes []TokenType            `protobuf:"varint,6,rep,packed,name=accepted_token_types,json=acceptedTokenTypes,proto3,enum=iam.authn.v2.TokenType" json:"accepted_token_types,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VerifyTokenRequest) GetForceRemote() bool {
	if x != nil {
		return x.ForceRemote
	}
	return false
}

func (x *VerifyTokenRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

func (x *VerifyTokenRequest) GetExpectedIssuer() string {
	if x != nil {
		return x.ExpectedIssuer
	}
	return ""
}

func (x *VerifyTokenRequest) GetExpectedAudience() []string {
	if x != nil {
		return x.ExpectedAudience
	}
	return nil
}

func (x *VerifyTokenRequest) GetAcceptedTokenTypes() []TokenType {
	if x != nil {
		return x.AcceptedTokenTypes
	}
	return nil
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Status        TokenStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=iam.authn.v2.TokenStatus" json:"status,omitempty"`
	Claims        *TokenClaims           `protobuf:"bytes,3,opt,name=claims,proto3" json:"claims,omitempty"`
	Metadata      *TokenMetadata         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	FailureReason string                 `protobuf:"bytes,5,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResponse) GetStatus() TokenStatus {
	if x != nil {
		return x.Status
	}
	return TokenStatus_TOKEN_STATUS_UNSPECIFIED
}

func (x *VerifyTokenResponse) GetClaims() *TokenClaims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *VerifyTokenResponse) GetMetadata() *TokenMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VerifyTokenResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Context       map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenPair     *TokenPair             `protobuf:"bytes,1,opt,name=token_pair,json=tokenPair,proto3" json:"token_pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenResponse) GetTokenPair() *TokenPair {
	if x != nil {
		return x.TokenPair
	}
	return nil
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Operator      *OperatorContext       `protobuf:"bytes,10,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RevokeTokenRequest) GetOperator() *OperatorContext {
	if x != nil {
		return x.Operator
	}
	return nil
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{11}
}

type RevokeRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Operator      *OperatorContext       `protobuf:"bytes,10,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRefreshTokenRequest) Reset() {
	*x = RevokeRefreshTokenRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshTokenRequest) ProtoMessage() {}

func (x *RevokeRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RevokeRefreshTokenRequest) GetOperator() *OperatorContext {
	if x != nil {
		return x.Operator
	}
	return nil
}

type RevokeRefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRefreshTokenResponse) Reset() {
	*x = RevokeRefreshTokenResponse{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshTokenResponse) ProtoMessage() {}

func (x *RevokeRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{13}
}

type SignupCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupCredential) Reset() {
	*x = SignupCredential{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupCredential) ProtoMessage() {}

func (x *SignupCredential) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupCredential.ProtoReflect.Descriptor instead.
func (*SignupCredential) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{14}
}

func (x *SignupCredential) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SignupCredential) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SignUpWithWechatMiniProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AppId         string                 `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	JsCode        string                 `protobuf:"bytes,5,opt,name=js_code,json=jsCode,proto3" json:"js_code,omitempty"`
	Nickname      string                 `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,20,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpWithWechatMiniProgramRequest) Reset() {
	*x = SignUpWithWechatMiniProgramRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpWithWechatMiniProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpWithWechatMiniProgramRequest) ProtoMessage() {}

func (x *SignUpWithWechatMiniProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpWithWechatMiniProgramRequest.ProtoReflect.Descriptor instead.
func (*SignUpWithWechatMiniProgramRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{15}
}

func (x *SignUpWithWechatMiniProgramRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpWithWechatMiniProgramRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SignUpWithWechatMiniProgramRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpWithWechatMiniProgramRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SignUpWithWechatMiniProgramRequest) GetJsCode() string {
	if x != nil {
		return x.JsCode
	}
	return ""
}

func (x *SignUpWithWechatMiniProgramRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SignUpWithWechatMiniProgramRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *SignUpWithWechatMiniProgramRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type SignupResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName        string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Phone           string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	LoginIdentityId string                 `protobuf:"bytes,5,opt,name=login_identity_id,json=loginIdentityId,proto3" json:"login_identity_id,omitempty"`
	Credential      *SignupCredential      `protobuf:"bytes,6,opt,name=credential,proto3" json:"credential,omitempty"`
	IsNewUser       bool                   `protobuf:"varint,7,opt,name=is_new_user,json=isNewUser,proto3" json:"is_new_user,omitempty"`
	IsNewIdentity   bool                   `protobuf:"varint,8,opt,name=is_new_identity,json=isNewIdentity,proto3" json:"is_new_identity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignupResult) Reset() {
	*x = SignupResult{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResult) ProtoMessage() {}

func (x *SignupResult) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResult.ProtoReflect.Descriptor instead.
func (*SignupResult) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{16}
}

func (x *SignupResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SignupResult) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SignupResult) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SignupResult) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupResult) GetLoginIdentityId() string {
	if x != nil {
		return x.LoginIdentityId
	}
	return ""
}

func (x *SignupResult) GetCredential() *SignupCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *SignupResult) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

func (x *SignupResult) GetIsNewIdentity() bool {
	if x != nil {
		return x.IsNewIdentity
	}
	return false
}

type SendLoginPhoneOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLoginPhoneOTPRequest) Reset() {
	*x = SendLoginPhoneOTPRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLoginPhoneOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLoginPhoneOTPRequest) ProtoMessage() {}

func (x *SendLoginPhoneOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLoginPhoneOTPRequest.ProtoReflect.Descriptor instead.
func (*SendLoginPhoneOTPRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{17}
}

func (x *SendLoginPhoneOTPRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{18}
}

func (x *MessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AuthenticatedUserContext struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	UserId                 string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrentLoginIdentityId string                 `protobuf:"bytes,2,opt,name=current_login_identity_id,json=currentLoginIdentityId,proto3" json:"current_login_identity_id,omitempty"`
	AuthenticatedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=authenticated_at,json=authenticatedAt,proto3" json:"authenticated_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthenticatedUserContext) Reset() {
	*x = AuthenticatedUserContext{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticatedUserContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatedUserContext) ProtoMessage() {}

func (x *AuthenticatedUserContext) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatedUserContext.ProtoReflect.Descriptor instead.
func (*AuthenticatedUserContext) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{19}
}

func (x *AuthenticatedUserContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthenticatedUserContext) GetCurrentLoginIdentityId() string {
	if x != nil {
		return x.CurrentLoginIdentityId
	}
	return ""
}

func (x *AuthenticatedUserContext) GetAuthenticatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AuthenticatedAt
	}
	return nil
}

type LoginIdentity struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider         string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Realm            string                 `protobuf:"bytes,4,opt,name=realm,proto3" json:"realm,omitempty"`
	Identifier       string                 `protobuf:"bytes,5,opt,name=identifier,proto3" json:"identifier,omitempty"`
	GlobalIdentifier string                 `protobuf:"bytes,6,opt,name=global_identifier,json=globalIdentifier,proto3" json:"global_identifier,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	VerifiedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	LinkedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=linked_at,json=linkedAt,proto3" json:"linked_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginIdentity) Reset() {
	*x = LoginIdentity{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginIdentity) ProtoMessage() {}

func (x *LoginIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginIdentity.ProtoReflect.Descriptor instead.
func (*LoginIdentity) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{20}
}

func (x *LoginIdentity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoginIdentity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginIdentity) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LoginIdentity) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *LoginIdentity) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginIdentity) GetGlobalIdentifier() string {
	if x != nil {
		return x.GlobalIdentifier
	}
	return ""
}

func (x *LoginIdentity) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginIdentity) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *LoginIdentity) GetLinkedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LinkedAt
	}
	return nil
}

type ListLoginIdentitiesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Actor         *AuthenticatedUserContext `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoginIdentitiesRequest) Reset() {
	*x = ListLoginIdentitiesRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoginIdentitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoginIdentitiesRequest) ProtoMessage() {}

func (x *ListLoginIdentitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoginIdentitiesRequest.ProtoReflect.Descriptor instead.
func (*ListLoginIdentitiesRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{21}
}

func (x *ListLoginIdentitiesRequest) GetActor() *AuthenticatedUserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ListLoginIdentitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LoginIdentity       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoginIdentitiesResponse) Reset() {
	*x = ListLoginIdentitiesResponse{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoginIdentitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoginIdentitiesResponse) ProtoMessage() {}

func (x *ListLoginIdentitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoginIdentitiesResponse.ProtoReflect.Descriptor instead.
func (*ListLoginIdentitiesResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{22}
}

func (x *ListLoginIdentitiesResponse) GetItems() []*LoginIdentity {
	if x != nil {
		return x.Items
	}
	return nil
}

type SendPhoneLinkChallengeRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Actor         *AuthenticatedUserContext `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Phone         string                    `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPhoneLinkChallengeRequest) Reset() {
	*x = SendPhoneLinkChallengeRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPhoneLinkChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPhoneLinkChallengeRequest) ProtoMessage() {}

func (x *SendPhoneLinkChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPhoneLinkChallengeRequest.ProtoReflect.Descriptor instead.
func (*SendPhoneLinkChallengeRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{23}
}

func (x *SendPhoneLinkChallengeRequest) GetActor() *AuthenticatedUserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *SendPhoneLinkChallengeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type LinkPhoneRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Actor         *AuthenticatedUserContext `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Phone         string                    `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	OtpCode       string                    `protobuf:"bytes,3,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkPhoneRequest) Reset() {
	*x = LinkPhoneRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkPhoneRequest) ProtoMessage() {}

func (x *LinkPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkPhoneRequest.ProtoReflect.Descriptor instead.
func (*LinkPhoneRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{24}
}

func (x *LinkPhoneRequest) GetActor() *AuthenticatedUserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *LinkPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LinkPhoneRequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

type LinkWechatMiniProgramRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Actor         *AuthenticatedUserContext `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	AppId         string                    `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Code          string                    `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkWechatMiniProgramRequest) Reset() {
	*x = LinkWechatMiniProgramRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkWechatMiniProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkWechatMiniProgramRequest) ProtoMessage() {}

func (x *LinkWechatMiniProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkWechatMiniProgramRequest.ProtoReflect.Descriptor instead.
func (*LinkWechatMiniProgramRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{25}
}

func (x *LinkWechatMiniProgramRequest) GetActor() *AuthenticatedUserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *LinkWechatMiniProgramRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *LinkWechatMiniProgramRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LinkWecomRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Actor         *AuthenticatedUserContext `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	CorpId        string                    `protobuf:"bytes,2,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty"`
	Code          string                    `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkWecomRequest) Reset() {
	*x = LinkWecomRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkWecomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkWecomRequest) ProtoMessage() {}

func (x *LinkWecomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkWecomRequest.ProtoReflect.Descriptor instead.
func (*LinkWecomRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{26}
}

func (x *LinkWecomRequest) GetActor() *AuthenticatedUserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *LinkWecomRequest) GetCorpId() string {
	if x != nil {
		return x.CorpId
	}
	return ""
}

func (x *LinkWecomRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UnlinkLoginIdentityRequest struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Actor           *AuthenticatedUserContext `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	LoginIdentityId string                    `protobuf:"bytes,2,opt,name=login_identity_id,json=loginIdentityId,proto3" json:"login_identity_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnlinkLoginIdentityRequest) Reset() {
	*x = UnlinkLoginIdentityRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkLoginIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkLoginIdentityRequest) ProtoMessage() {}

func (x *UnlinkLoginIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkLoginIdentityRequest.ProtoReflect.Descriptor instead.
func (*UnlinkLoginIdentityRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{27}
}

func (x *UnlinkLoginIdentityRequest) GetActor() *AuthenticatedUserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *UnlinkLoginIdentityRequest) GetLoginIdentityId() string {
	if x != nil {
		return x.LoginIdentityId
	}
	return ""
}

type LinkLoginIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginIdentity *LoginIdentity         `protobuf:"bytes,1,opt,name=login_identity,json=loginIdentity,proto3" json:"login_identity,omitempty"`
	Reused        bool                   `protobuf:"varint,2,opt,name=reused,proto3" json:"reused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkLoginIdentityResponse) Reset() {
	*x = LinkLoginIdentityResponse{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkLoginIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkLoginIdentityResponse) ProtoMessage() {}

func (x *LinkLoginIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkLoginIdentityResponse.ProtoReflect.Descriptor instead.
func (*LinkLoginIdentityResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{28}
}

func (x *LinkLoginIdentityResponse) GetLoginIdentity() *LoginIdentity {
	if x != nil {
		return x.LoginIdentity
	}
	return nil
}

func (x *LinkLoginIdentityResponse) GetReused() bool {
	if x != nil {
		return x.Reused
	}
	return false
}

type GetJWKSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWKSRequest) Reset() {
	*x = GetJWKSRequest{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWKSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWKSRequest) ProtoMessage() {}

func (x *GetJWKSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWKSRequest.ProtoReflect.Descriptor instead.
func (*GetJWKSRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{29}
}

type GetJWKSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwks          []byte                 `protobuf:"bytes,1,opt,name=jwks,proto3" json:"jwks,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	LastModified  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWKSResponse) Reset() {
	*x = GetJWKSResponse{}
	mi := &file_iam_authn_v2_authn_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWKSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWKSResponse) ProtoMessage() {}

func (x *GetJWKSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v2_authn_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWKSResponse.ProtoReflect.Descriptor instead.
func (*GetJWKSResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v2_authn_proto_rawDescGZIP(), []int{30}
}

func (x *GetJWKSResponse) GetJwks() []byte {
	if x != nil {
		return x.Jwks
	}
	return nil
}

func (x *GetJWKSResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *GetJWKSResponse) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

var File_iam_authn_v2_authn_proto protoreflect.FileDescriptor

const file_iam_authn_v2_authn_proto_rawDesc = "" +
	"\n" +
	"\x18iam/authn/v2/authn.proto\x12\fiam.authn.v2\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x02\n" +
	"\x0fOperatorContext\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\tR\n" +
	"operatorId\x12#\n" +
	"\roperator_name\x18\x02 \x01(\tR\foperatorName\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12>\n" +
	"\x05extra\x18\n" +
	" \x03(\v2(.iam.authn.v2.OperatorContext.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfd\x05\n" +
	"\vTokenClaims\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12*\n" +
	"\x11login_identity_id\x18\x04 \x01(\tR\x0floginIdentityId\x12\x16\n" +
	"\x06issuer\x18\x05 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x06 \x03(\tR\baudience\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\x126\n" +
	"\n" +
	"token_type\x18\t \x01(\x0e2\x17.iam.authn.v2.TokenTypeR\ttokenType\x127\n" +
	"\tissued_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12E\n" +
	"\x10authenticated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0fauthenticatedAt\x129\n" +
	"\n" +
	"not_before\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x12I\n" +
	"\n" +
	"attributes\x18\x14 \x03(\v2).iam.authn.v2.TokenClaims.AttributesEntryR\n" +
	"attributes\x12\x10\n" +
	"\x03amr\x18\x15 \x03(\tR\x03amr\x12\x15\n" +
	"\x06org_id\x18\x16 \x01(\tR\x05orgId\x12#\n" +
	"\rtenant_domain\x18\x17 \x01(\tR\ftenantDomain\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\tTokenPair\x12\x1d\n" +
	"\n" +
	"token_type\x18\x01 \x01(\tR\ttokenType\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x128\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\texpiresIn\"\xee\x01\n" +
	"\rTokenMetadata\x126\n" +
	"\n" +
	"token_type\x18\x01 \x01(\x0e2\x17.iam.authn.v2.TokenTypeR\ttokenType\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.iam.authn.v2.TokenStatusR\x06status\x127\n" +
	"\tissued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x8c\x01\n" +
	"\fLoginRequest\x12\x1f\n" +
	"\vauth_method\x18\x01 \x01(\tR\n" +
	"authMethod\x12>\n" +
	"\x0emethod_payload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\rmethodPayload\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"G\n" +
	"\rLoginResponse\x126\n" +
	"\n" +
	"token_pair\x18\x01 \x01(\v2\x17.iam.authn.v2.TokenPairR\ttokenPair\"\xa6\x02\n" +
	"\x12VerifyTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12!\n" +
	"\fforce_remote\x18\x02 \x01(\bR\vforceRemote\x12)\n" +
	"\x10include_metadata\x18\x03 \x01(\bR\x0fincludeMetadata\x12'\n" +
	"\x0fexpected_issuer\x18\x04 \x01(\tR\x0eexpectedIssuer\x12+\n" +
	"\x11expected_audience\x18\x05 \x03(\tR\x10expectedAudience\x12I\n" +
	"\x14accepted_token_types\x18\x06 \x03(\x0e2\x17.iam.authn.v2.TokenTypeR\x12acceptedTokenTypes\"\xf1\x01\n" +
	"\x13VerifyTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.iam.authn.v2.TokenStatusR\x06status\x121\n" +
	"\x06claims\x18\x03 \x01(\v2\x19.iam.authn.v2.TokenClaimsR\x06claims\x127\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1b.iam.authn.v2.TokenMetadataR\bmetadata\x12%\n" +
	"\x0efailure_reason\x18\x05 \x01(\tR\rfailureReason\"\xc0\x01\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12H\n" +
	"\acontext\x18\x02 \x03(\v2..iam.authn.v2.RefreshTokenRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x14RefreshTokenResponse\x126\n" +
	"\n" +
	"token_pair\x18\x01 \x01(\v2\x17.iam.authn.v2.TokenPairR\ttokenPair\"r\n" +
	"\x12RevokeTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x129\n" +
	"\boperator\x18\n" +
	" \x01(\v2\x1d.iam.authn.v2.OperatorContextR\boperator\"\x15\n" +
	"\x13RevokeTokenResponse\"{\n" +
	"\x19RevokeRefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x129\n" +
	"\boperator\x18\n" +
	" \x01(\v2\x1d.iam.authn.v2.OperatorContextR\boperator\"\x1c\n" +
	"\x1aRevokeRefreshTokenResponse\"6\n" +
	"\x10SignupCredential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xd1\x02\n" +
	"\"SignUpWithWechatMiniProgramRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\tR\x05appId\x12\x17\n" +
	"\ajs_code\x18\x05 \x01(\tR\x06jsCode\x12\x1a\n" +
	"\bnickname\x18\x06 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12N\n" +
	"\x04meta\x18\x14 \x03(\v2:.iam.authn.v2.SignUpWithWechatMiniProgramRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x02\n" +
	"\fSignupResult\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12*\n" +
	"\x11login_identity_id\x18\x05 \x01(\tR\x0floginIdentityId\x12>\n" +
	"\n" +
	"credential\x18\x06 \x01(\v2\x1e.iam.authn.v2.SignupCredentialR\n" +
	"credential\x12\x1e\n" +
	"\vis_new_user\x18\a \x01(\bR\tisNewUser\x12&\n" +
	"\x0fis_new_identity\x18\b \x01(\bR\risNewIdentity\"0\n" +
	"\x18SendLoginPhoneOTPRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"+\n" +
	"\x0fMessageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb5\x01\n" +
	"\x18AuthenticatedUserContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\x19current_login_identity_id\x18\x02 \x01(\tR\x16currentLoginIdentityId\x12E\n" +
	"\x10authenticated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0fauthenticatedAt\"\xc5\x02\n" +
	"\rLoginIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x14\n" +
	"\x05realm\x18\x04 \x01(\tR\x05realm\x12\x1e\n" +
	"\n" +
	"identifier\x18\x05 \x01(\tR\n" +
	"identifier\x12+\n" +
	"\x11global_identifier\x18\x06 \x01(\tR\x10globalIdentifier\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12;\n" +
	"\vverified_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x127\n" +
	"\tlinked_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\blinkedAt\"Z\n" +
	"\x1aListLoginIdentitiesRequest\x12<\n" +
	"\x05actor\x18\x01 \x01(\v2&.iam.authn.v2.AuthenticatedUserContextR\x05actor\"P\n" +
	"\x1bListLoginIdentitiesResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.iam.authn.v2.LoginIdentityR\x05items\"s\n" +
	"\x1dSendPhoneLinkChallengeRequest\x12<\n" +
	"\x05actor\x18\x01 \x01(\v2&.iam.authn.v2.AuthenticatedUserContextR\x05actor\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"\x81\x01\n" +
	"\x10LinkPhoneRequest\x12<\n" +
	"\x05actor\x18\x01 \x01(\v2&.iam.authn.v2.AuthenticatedUserContextR\x05actor\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x19\n" +
	"\botp_code\x18\x03 \x01(\tR\aotpCode\"\x87\x01\n" +
	"\x1cLinkWechatMiniProgramRequest\x12<\n" +
	"\x05actor\x18\x01 \x01(\v2&.iam.authn.v2.AuthenticatedUserContextR\x05actor\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"}\n" +
	"\x10LinkWecomRequest\x12<\n" +
	"\x05actor\x18\x01 \x01(\v2&.iam.authn.v2.AuthenticatedUserContextR\x05actor\x12\x17\n" +
	"\acorp_id\x18\x02 \x01(\tR\x06corpId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\x86\x01\n" +
	"\x1aUnlinkLoginIdentityRequest\x12<\n" +
	"\x05actor\x18\x01 \x01(\v2&.iam.authn.v2.AuthenticatedUserContextR\x05actor\x12*\n" +
	"\x11login_identity_id\x18\x02 \x01(\tR\x0floginIdentityId\"w\n" +
	"\x19LinkLoginIdentityResponse\x12B\n" +
	"\x0elogin_identity\x18\x01 \x01(\v2\x1b.iam.authn.v2.LoginIdentityR\rloginIdentity\x12\x16\n" +
	"\x06reused\x18\x02 \x01(\bR\x06reused\"\x10\n" +
	"\x0eGetJWKSRequest\"z\n" +
	"\x0fGetJWKSResponse\x12\x12\n" +
	"\x04jwks\x18\x01 \x01(\fR\x04jwks\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x12?\n" +
	"\rlast_modified\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified*w\n" +
	"\vTokenStatus\x12\x1c\n" +
	"\x18TOKEN_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TOKEN_STATUS_VALID\x10\x01\x12\x18\n" +
	"\x14TOKEN_STATUS_REVOKED\x10\x02\x12\x18\n" +
	"\x14TOKEN_STATUS_EXPIRED\x10\x03*p\n" +
	"\tTokenType\x12\x1a\n" +
	"\x16TOKEN_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TOKEN_TYPE_ACCESS\x10\x01\x12\x16\n" +
	"\x12TOKEN_TYPE_REFRESH\x10\x02\"\x04\b\x03\x10\x03*\x12TOKEN_TYPE_SERVICE2\xb7\x03\n" +
	"\vAuthService\x12@\n" +
	"\x05Login\x12\x1a.iam.authn.v2.LoginRequest\x1a\x1b.iam.authn.v2.LoginResponse\x12R\n" +
	"\vVerifyToken\x12 .iam.authn.v2.VerifyTokenRequest\x1a!.iam.authn.v2.VerifyTokenResponse\x12U\n" +
	"\fRefreshToken\x12!.iam.authn.v2.RefreshTokenRequest\x1a\".iam.authn.v2.RefreshTokenResponse\x12R\n" +
	"\vRevokeToken\x12 .iam.authn.v2.RevokeTokenRequest\x1a!.iam.authn.v2.RevokeTokenResponse\x12g\n" +
	"\x12RevokeRefreshToken\x12'.iam.authn.v2.RevokeRefreshTokenRequest\x1a(.iam.authn.v2.RevokeRefreshTokenResponse2\x80\x01\n" +
	"\x11AuthSignupService\x12k\n" +
	"\x1bSignUpWithWechatMiniProgram\x120.iam.authn.v2.SignUpWithWechatMiniProgramRequest\x1a\x1a.iam.authn.v2.SignupResult2r\n" +
	"\x14AuthChallengeService\x12Z\n" +
	"\x11SendLoginPhoneOTP\x12&.iam.authn.v2.SendLoginPhoneOTPRequest\x1a\x1d.iam.authn.v2.MessageResponse2\xe2\x04\n" +
	"\x14LoginIdentityService\x12j\n" +
	"\x13ListLoginIdentities\x12(.iam.authn.v2.ListLoginIdentitiesRequest\x1a).iam.authn.v2.ListLoginIdentitiesResponse\x12d\n" +
	"\x16SendPhoneLinkChallenge\x12+.iam.authn.v2.SendPhoneLinkChallengeRequest\x1a\x1d.iam.authn.v2.MessageResponse\x12T\n" +
	"\tLinkPhone\x12\x1e.iam.authn.v2.LinkPhoneRequest\x1a'.iam.authn.v2.LinkLoginIdentityResponse\x12l\n" +
	"\x15LinkWechatMiniProgram\x12*.iam.authn.v2.LinkWechatMiniProgramRequest\x1a'.iam.authn.v2.LinkLoginIdentityResponse\x12T\n" +
	"\tLinkWecom\x12\x1e.iam.authn.v2.LinkWecomRequest\x1a'.iam.authn.v2.LinkLoginIdentityResponse\x12^\n" +
	"\x13UnlinkLoginIdentity\x12(.iam.authn.v2.UnlinkLoginIdentityRequest\x1a\x1d.iam.authn.v2.MessageResponse2U\n" +
	"\vJWKSService\x12F\n" +
	"\aGetJWKS\x12\x1c.iam.authn.v2.GetJWKSRequest\x1a\x1d.iam.authn.v2.GetJWKSResponseB>Z<github.com/FangcunMount/iam/v4/api/grpc/iam/authn/v2;authnv2b\x06proto3"

var (
	file_iam_authn_v2_authn_proto_rawDescOnce sync.Once
	file_iam_authn_v2_authn_proto_rawDescData []byte
)

func file_iam_authn_v2_authn_proto_rawDescGZIP() []byte {
	file_iam_authn_v2_authn_proto_rawDescOnce.Do(func() {
		file_iam_authn_v2_authn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_authn_v2_authn_proto_rawDesc), len(file_iam_authn_v2_authn_proto_rawDesc)))
	})
	return file_iam_authn_v2_authn_proto_rawDescData
}

var file_iam_authn_v2_authn_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_iam_authn_v2_authn_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_iam_authn_v2_authn_proto_goTypes = []any{
	(TokenStatus)(0),                           // 0: iam.authn.v2.TokenStatus
	(TokenType)(0),                             // 1: iam.authn.v2.TokenType
	(*OperatorContext)(nil),                    // 2: iam.authn.v2.OperatorContext
	(*TokenClaims)(nil),                        // 3: iam.authn.v2.TokenClaims
	(*TokenPair)(nil),                          // 4: iam.authn.v2.TokenPair
	(*TokenMetadata)(nil),                      // 5: iam.authn.v2.TokenMetadata
	(*LoginRequest)(nil),                       // 6: iam.authn.v2.LoginRequest
	(*LoginResponse)(nil),                      // 7: iam.authn.v2.LoginResponse
	(*VerifyTokenRequest)(nil),                 // 8: iam.authn.v2.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),                // 9: iam.authn.v2.VerifyTokenResponse
	(*RefreshTokenRequest)(nil),                // 10: iam.authn.v2.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),               // 11: iam.authn.v2.RefreshTokenResponse
	(*RevokeTokenRequest)(nil),                 // 12: iam.authn.v2.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),                // 13: iam.authn.v2.RevokeTokenResponse
	(*RevokeRefreshTokenRequest)(nil),          // 14: iam.authn.v2.RevokeRefreshTokenRequest
	(*RevokeRefreshTokenResponse)(nil),         // 15: iam.authn.v2.RevokeRefreshTokenResponse
	(*SignupCredential)(nil),                   // 16: iam.authn.v2.SignupCredential
	(*SignUpWithWechatMiniProgramRequest)(nil), // 17: iam.authn.v2.SignUpWithWechatMiniProgramRequest
	(*SignupResult)(nil),                       // 18: iam.authn.v2.SignupResult
	(*SendLoginPhoneOTPRequest)(nil),           // 19: iam.authn.v2.SendLoginPhoneOTPRequest
	(*MessageResponse)(nil),                    // 20: iam.authn.v2.MessageResponse
	(*AuthenticatedUserContext)(nil),           // 21: iam.authn.v2.AuthenticatedUserContext
	(*LoginIdentity)(nil),                      // 22: iam.authn.v2.LoginIdentity
	(*ListLoginIdentitiesRequest)(nil),         // 23: iam.authn.v2.ListLoginIdentitiesRequest
	(*ListLoginIdentitiesResponse)(nil),        // 24: iam.authn.v2.ListLoginIdentitiesResponse
	(*SendPhoneLinkChallengeRequest)(nil),      // 25: iam.authn.v2.SendPhoneLinkChallengeRequest
	(*LinkPhoneRequest)(nil),                   // 26: iam.authn.v2.LinkPhoneRequest
	(*LinkWechatMiniProgramRequest)(nil),       // 27: iam.authn.v2.LinkWechatMiniProgramRequest
	(*LinkWecomRequest)(nil),                   // 28: iam.authn.v2.LinkWecomRequest
	(*UnlinkLoginIdentityRequest)(nil),         // 29: iam.authn.v2.UnlinkLoginIdentityRequest
	(*LinkLoginIdentityResponse)(nil),          // 30: iam.authn.v2.LinkLoginIdentityResponse
	(*GetJWKSRequest)(nil),                     // 31: iam.authn.v2.GetJWKSRequest
	(*GetJWKSResponse)(nil),                    // 32: iam.authn.v2.GetJWKSResponse
	nil,                                        // 33: iam.authn.v2.OperatorContext.ExtraEntry
	nil,                                        // 34: iam.authn.v2.TokenClaims.AttributesEntry
	nil,                                        // 35: iam.authn.v2.RefreshTokenRequest.ContextEntry
	nil,                                        // 36: iam.authn.v2.SignUpWithWechatMiniProgramRequest.MetaEntry
	(*timestamppb.Timestamp)(nil),              // 37: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                // 38: google.protobuf.Duration
	(*structpb.Struct)(nil),                    // 39: google.protobuf.Struct
}
var file_iam_authn_v2_authn_proto_depIdxs = []int32{
	33, // 0: iam.authn.v2.OperatorContext.extra:type_name -> iam.authn.v2.OperatorContext.ExtraEntry
	1,  // 1: iam.authn.v2.TokenClaims.token_type:type_name -> iam.authn.v2.TokenType
	37, // 2: iam.authn.v2.TokenClaims.issued_at:type_name -> google.protobuf.Timestamp
	37, // 3: iam.authn.v2.TokenClaims.expires_at:type_name -> google.protobuf.Timestamp
	37, // 4: iam.authn.v2.TokenClaims.authenticated_at:type_name -> google.protobuf.Timestamp
	37, // 5: iam.authn.v2.TokenClaims.not_before:type_name -> google.protobuf.Timestamp
	34, // 6: iam.authn.v2.TokenClaims.attributes:type_name -> iam.authn.v2.TokenClaims.AttributesEntry
	38, // 7: iam.authn.v2.TokenPair.expires_in:type_name -> google.protobuf.Duration
	1,  // 8: iam.authn.v2.TokenMetadata.token_type:type_name -> iam.authn.v2.TokenType
	0,  // 9: iam.authn.v2.TokenMetadata.status:type_name -> iam.authn.v2.TokenStatus
	37, // 10: iam.authn.v2.TokenMetadata.issued_at:type_name -> google.protobuf.Timestamp
	37, // 11: iam.authn.v2.TokenMetadata.expires_at:type_name -> google.protobuf.Timestamp
	39, // 12: iam.authn.v2.LoginRequest.method_payload:type_name -> google.protobuf.Struct
	4,  // 13: iam.authn.v2.LoginResponse.token_pair:type_name -> iam.authn.v2.TokenPair
	1,  // 14: iam.authn.v2.VerifyTokenRequest.accepted_token_types:type_name -> iam.authn.v2.TokenType
	0,  // 15: iam.authn.v2.VerifyTokenResponse.status:type_name -> iam.authn.v2.TokenStatus
	3,  // 16: iam.authn.v2.VerifyTokenResponse.claims:type_name -> iam.authn.v2.TokenClaims
	5,  // 17: iam.authn.v2.VerifyTokenResponse.metadata:type_name -> iam.authn.v2.TokenMetadata
	35, // 18: iam.authn.v2.RefreshTokenRequest.context:type_name -> iam.authn.v2.RefreshTokenRequest.ContextEntry
	4,  // 19: iam.authn.v2.RefreshTokenResponse.token_pair:type_name -> iam.authn.v2.TokenPair
	2,  // 20: iam.authn.v2.RevokeTokenRequest.operator:type_name -> iam.authn.v2.OperatorContext
	2,  // 21: iam.authn.v2.RevokeRefreshTokenRequest.operator:type_name -> iam.authn.v2.OperatorContext
	36, // 22: iam.authn.v2.SignUpWithWechatMiniProgramRequest.meta:type_name -> iam.authn.v2.SignUpWithWechatMiniProgramRequest.MetaEntry
	16, // 23: iam.authn.v2.SignupResult.credential:type_name -> iam.authn.v2.SignupCredential
	37, // 24: iam.authn.v2.AuthenticatedUserContext.authenticated_at:type_name -> google.protobuf.Timestamp
	37, // 25: iam.authn.v2.LoginIdentity.verified_at:type_name -> google.protobuf.Timestamp
	37, // 26: iam.authn.v2.LoginIdentity.linked_at:type_name -> google.protobuf.Timestamp
	21, // 27: iam.authn.v2.ListLoginIdentitiesRequest.actor:type_name -> iam.authn.v2.AuthenticatedUserContext
	22, // 28: iam.authn.v2.ListLoginIdentitiesResponse.items:type_name -> iam.authn.v2.LoginIdentity
	21, // 29: iam.authn.v2.SendPhoneLinkChallengeRequest.actor:type_name -> iam.authn.v2.AuthenticatedUserContext
	21, // 30: iam.authn.v2.LinkPhoneRequest.actor:type_name -> iam.authn.v2.AuthenticatedUserContext
	21, // 31: iam.authn.v2.LinkWechatMiniProgramRequest.actor:type_name -> iam.authn.v2.AuthenticatedUserContext
	21, // 32: iam.authn.v2.LinkWecomRequest.actor:type_name -> iam.authn.v2.AuthenticatedUserContext
	21, // 33: iam.authn.v2.UnlinkLoginIdentityRequest.actor:type_name -> iam.authn.v2.AuthenticatedUserContext
	22, // 34: iam.authn.v2.LinkLoginIdentityResponse.login_identity:type_name -> iam.authn.v2.LoginIdentity
	37, // 35: iam.authn.v2.GetJWKSResponse.last_modified:type_name -> google.protobuf.Timestamp
	6,  // 36: iam.authn.v2.AuthService.Login:input_type -> iam.authn.v2.LoginRequest
	8,  // 37: iam.authn.v2.AuthService.VerifyToken:input_type -> iam.authn.v2.VerifyTokenRequest
	10, // 38: iam.authn.v2.AuthService.RefreshToken:input_type -> iam.authn.v2.RefreshTokenRequest
	12, // 39: iam.authn.v2.AuthService.RevokeToken:input_type -> iam.authn.v2.RevokeTokenRequest
	14, // 40: iam.authn.v2.AuthService.RevokeRefreshToken:input_type -> iam.authn.v2.RevokeRefreshTokenRequest
	17, // 41: iam.authn.v2.AuthSignupService.SignUpWithWechatMiniProgram:input_type -> iam.authn.v2.SignUpWithWechatMiniProgramRequest
	19, // 42: iam.authn.v2.AuthChallengeService.SendLoginPhoneOTP:input_type -> iam.authn.v2.SendLoginPhoneOTPRequest
	23, // 43: iam.authn.v2.LoginIdentityService.ListLoginIdentities:input_type -> iam.authn.v2.ListLoginIdentitiesRequest
	25, // 44: iam.authn.v2.LoginIdentityService.SendPhoneLinkChallenge:input_type -> iam.authn.v2.SendPhoneLinkChallengeRequest
	26, // 45: iam.authn.v2.LoginIdentityService.LinkPhone:input_type -> iam.authn.v2.LinkPhoneRequest
	27, // 46: iam.authn.v2.LoginIdentityService.LinkWechatMiniProgram:input_type -> iam.authn.v2.LinkWechatMiniProgramRequest
	28, // 47: iam.authn.v2.LoginIdentityService.LinkWecom:input_type -> iam.authn.v2.LinkWecomRequest
	29, // 48: iam.authn.v2.LoginIdentityService.UnlinkLoginIdentity:input_type -> iam.authn.v2.UnlinkLoginIdentityRequest
	31, // 49: iam.authn.v2.JWKSService.GetJWKS:input_type -> iam.authn.v2.GetJWKSRequest
	7,  // 50: iam.authn.v2.AuthService.Login:output_type -> iam.authn.v2.LoginResponse
	9,  // 51: iam.authn.v2.AuthService.VerifyToken:output_type -> iam.authn.v2.VerifyTokenResponse
	11, // 52: iam.authn.v2.AuthService.RefreshToken:output_type -> iam.authn.v2.RefreshTokenResponse
	13, // 53: iam.authn.v2.AuthService.RevokeToken:output_type -> iam.authn.v2.RevokeTokenResponse
	15, // 54: iam.authn.v2.AuthService.RevokeRefreshToken:output_type -> iam.authn.v2.RevokeRefreshTokenResponse
	18, // 55: iam.authn.v2.AuthSignupService.SignUpWithWechatMiniProgram:output_type -> iam.authn.v2.SignupResult
	20, // 56: iam.authn.v2.AuthChallengeService.SendLoginPhoneOTP:output_type -> iam.authn.v2.MessageResponse
	24, // 57: iam.authn.v2.LoginIdentityService.ListLoginIdentities:output_type -> iam.authn.v2.ListLoginIdentitiesResponse
	20, // 58: iam.authn.v2.LoginIdentityService.SendPhoneLinkChallenge:output_type -> iam.authn.v2.MessageResponse
	30, // 59: iam.authn.v2.LoginIdentityService.LinkPhone:output_type -> iam.authn.v2.LinkLoginIdentityResponse
	30, // 60: iam.authn.v2.LoginIdentityService.LinkWechatMiniProgram:output_type -> iam.authn.v2.LinkLoginIdentityResponse
	30, // 61: iam.authn.v2.LoginIdentityService.LinkWecom:output_type -> iam.authn.v2.LinkLoginIdentityResponse
	20, // 62: iam.authn.v2.LoginIdentityService.UnlinkLoginIdentity:output_type -> iam.authn.v2.MessageResponse
	32, // 63: iam.authn.v2.JWKSService.GetJWKS:output_type -> iam.authn.v2.GetJWKSResponse
	50, // [50:64] is the sub-list for method output_type
	36, // [36:50] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_iam_authn_v2_authn_proto_init() }
func file_iam_authn_v2_authn_proto_init() {
	if File_iam_authn_v2_authn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_authn_v2_authn_proto_rawDesc), len(file_iam_authn_v2_authn_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_iam_authn_v2_authn_proto_goTypes,
		DependencyIndexes: file_iam_authn_v2_authn_proto_depIdxs,
		EnumInfos:         file_iam_authn_v2_authn_proto_enumTypes,
		MessageInfos:      file_iam_authn_v2_authn_proto_msgTypes,
	}.Build()
	File_iam_authn_v2_authn_proto = out.File
	file_iam_authn_v2_authn_proto_goTypes = nil
	file_iam_authn_v2_authn_proto_depIdxs = nil
}
