// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: iam/idp/v1/idp.proto

package idpv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IDPService_GetWechatApp_FullMethodName = "/iam.idp.v1.IDPService/GetWechatApp"
)

// IDPServiceClient is the client API for IDPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IDP 服务（身份提供者服务）
type IDPServiceClient interface {
	// 根据 AppID 查询微信应用
	GetWechatApp(ctx context.Context, in *GetWechatAppRequest, opts ...grpc.CallOption) (*GetWechatAppResponse, error)
}

type iDPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIDPServiceClient(cc grpc.ClientConnInterface) IDPServiceClient {
	return &iDPServiceClient{cc}
}

func (c *iDPServiceClient) GetWechatApp(ctx context.Context, in *GetWechatAppRequest, opts ...grpc.CallOption) (*GetWechatAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWechatAppResponse)
	err := c.cc.Invoke(ctx, IDPService_GetWechatApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDPServiceServer is the server API for IDPService service.
// All implementations must embed UnimplementedIDPServiceServer
// for forward compatibility.
//
// IDP 服务（身份提供者服务）
type IDPServiceServer interface {
	// 根据 AppID 查询微信应用
	GetWechatApp(context.Context, *GetWechatAppRequest) (*GetWechatAppResponse, error)
	mustEmbedUnimplementedIDPServiceServer()
}

// UnimplementedIDPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIDPServiceServer struct{}

func (UnimplementedIDPServiceServer) GetWechatApp(context.Context, *GetWechatAppRequest) (*GetWechatAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWechatApp not implemented")
}
func (UnimplementedIDPServiceServer) mustEmbedUnimplementedIDPServiceServer() {}
func (UnimplementedIDPServiceServer) testEmbeddedByValue()                    {}

// UnsafeIDPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IDPServiceServer will
// result in compilation errors.
type UnsafeIDPServiceServer interface {
	mustEmbedUnimplementedIDPServiceServer()
}

func RegisterIDPServiceServer(s grpc.ServiceRegistrar, srv IDPServiceServer) {
	// If the following call pancis, it indicates UnimplementedIDPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IDPService_ServiceDesc, srv)
}

func _IDPService_GetWechatApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWechatAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDPServiceServer).GetWechatApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IDPService_GetWechatApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDPServiceServer).GetWechatApp(ctx, req.(*GetWechatAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IDPService_ServiceDesc is the grpc.ServiceDesc for IDPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IDPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.idp.v1.IDPService",
	HandlerType: (*IDPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWechatApp",
			Handler:    _IDPService_GetWechatApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iam/idp/v1/idp.proto",
}
