// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: iam/idp/v2/idp.proto

package idpv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 微信应用类型
type WechatAppType int32

const (
	WechatAppType_WECHAT_APP_TYPE_UNSPECIFIED           WechatAppType = 0
	WechatAppType_WECHAT_APP_TYPE_MINI_PROGRAM          WechatAppType = 1 // 小程序
	WechatAppType_WECHAT_APP_TYPE_MP                    WechatAppType = 2 // 公众号
	WechatAppType_WECHAT_APP_TYPE_OPEN_PLATFORM_WEBSITE WechatAppType = 3 // 微信开放平台网站应用（PC Web 扫码登录）
)

// Enum value maps for WechatAppType.
var (
	WechatAppType_name = map[int32]string{
		0: "WECHAT_APP_TYPE_UNSPECIFIED",
		1: "WECHAT_APP_TYPE_MINI_PROGRAM",
		2: "WECHAT_APP_TYPE_MP",
		3: "WECHAT_APP_TYPE_OPEN_PLATFORM_WEBSITE",
	}
	WechatAppType_value = map[string]int32{
		"WECHAT_APP_TYPE_UNSPECIFIED":           0,
		"WECHAT_APP_TYPE_MINI_PROGRAM":          1,
		"WECHAT_APP_TYPE_MP":                    2,
		"WECHAT_APP_TYPE_OPEN_PLATFORM_WEBSITE": 3,
	}
)

func (x WechatAppType) Enum() *WechatAppType {
	p := new(WechatAppType)
	*p = x
	return p
}

func (x WechatAppType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WechatAppType) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_idp_v2_idp_proto_enumTypes[0].Descriptor()
}

func (WechatAppType) Type() protoreflect.EnumType {
	return &file_iam_idp_v2_idp_proto_enumTypes[0]
}

func (x WechatAppType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WechatAppType.Descriptor instead.
func (WechatAppType) EnumDescriptor() ([]byte, []int) {
	return file_iam_idp_v2_idp_proto_rawDescGZIP(), []int{0}
}

// 微信应用状态
type WechatAppStatus int32

const (
	WechatAppStatus_WECHAT_APP_STATUS_UNSPECIFIED WechatAppStatus = 0
	WechatAppStatus_WECHAT_APP_STATUS_ENABLED     WechatAppStatus = 1 // 启用
	WechatAppStatus_WECHAT_APP_STATUS_DISABLED    WechatAppStatus = 2 // 禁用
	WechatAppStatus_WECHAT_APP_STATUS_ARCHIVED    WechatAppStatus = 3 // 归档
)

// Enum value maps for WechatAppStatus.
var (
	WechatAppStatus_name = map[int32]string{
		0: "WECHAT_APP_STATUS_UNSPECIFIED",
		1: "WECHAT_APP_STATUS_ENABLED",
		2: "WECHAT_APP_STATUS_DISABLED",
		3: "WECHAT_APP_STATUS_ARCHIVED",
	}
	WechatAppStatus_value = map[string]int32{
		"WECHAT_APP_STATUS_UNSPECIFIED": 0,
		"WECHAT_APP_STATUS_ENABLED":     1,
		"WECHAT_APP_STATUS_DISABLED":    2,
		"WECHAT_APP_STATUS_ARCHIVED":    3,
	}
)

func (x WechatAppStatus) Enum() *WechatAppStatus {
	p := new(WechatAppStatus)
	*p = x
	return p
}

func (x WechatAppStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WechatAppStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_idp_v2_idp_proto_enumTypes[1].Descriptor()
}

func (WechatAppStatus) Type() protoreflect.EnumType {
	return &file_iam_idp_v2_idp_proto_enumTypes[1]
}

func (x WechatAppStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WechatAppStatus.Descriptor instead.
func (WechatAppStatus) EnumDescriptor() ([]byte, []int) {
	return file_iam_idp_v2_idp_proto_rawDescGZIP(), []int{1}
}

// 微信应用
type WechatApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                          // 内部 ID
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                       // 微信应用 ID
	AppSecret     string                 `protobuf:"bytes,3,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`           // 微信应用密钥（AppSecret）
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                      // 应用名称
	Type          WechatAppType          `protobuf:"varint,5,opt,name=type,proto3,enum=iam.idp.v2.WechatAppType" json:"type,omitempty"`       // 应用类型
	Status        WechatAppStatus        `protobuf:"varint,6,opt,name=status,proto3,enum=iam.idp.v2.WechatAppStatus" json:"status,omitempty"` // 应用状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WechatApp) Reset() {
	*x = WechatApp{}
	mi := &file_iam_idp_v2_idp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WechatApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatApp) ProtoMessage() {}

func (x *WechatApp) ProtoReflect() protoreflect.Message {
	mi := &file_iam_idp_v2_idp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatApp.ProtoReflect.Descriptor instead.
func (*WechatApp) Descriptor() ([]byte, []int) {
	return file_iam_idp_v2_idp_proto_rawDescGZIP(), []int{0}
}

func (x *WechatApp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WechatApp) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WechatApp) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *WechatApp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WechatApp) GetType() WechatAppType {
	if x != nil {
		return x.Type
	}
	return WechatAppType_WECHAT_APP_TYPE_UNSPECIFIED
}

func (x *WechatApp) GetStatus() WechatAppStatus {
	if x != nil {
		return x.Status
	}
	return WechatAppStatus_WECHAT_APP_STATUS_UNSPECIFIED
}

// 查询微信应用请求
type GetWechatAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"` // 微信应用 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWechatAppRequest) Reset() {
	*x = GetWechatAppRequest{}
	mi := &file_iam_idp_v2_idp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWechatAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWechatAppRequest) ProtoMessage() {}

func (x *GetWechatAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_idp_v2_idp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWechatAppRequest.ProtoReflect.Descriptor instead.
func (*GetWechatAppRequest) Descriptor() ([]byte, []int) {
	return file_iam_idp_v2_idp_proto_rawDescGZIP(), []int{1}
}

func (x *GetWechatAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// 查询微信应用响应
type GetWechatAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *WechatApp             `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWechatAppResponse) Reset() {
	*x = GetWechatAppResponse{}
	mi := &file_iam_idp_v2_idp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWechatAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWechatAppResponse) ProtoMessage() {}

func (x *GetWechatAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_idp_v2_idp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWechatAppResponse.ProtoReflect.Descriptor instead.
func (*GetWechatAppResponse) Descriptor() ([]byte, []int) {
	return file_iam_idp_v2_idp_proto_rawDescGZIP(), []int{2}
}

func (x *GetWechatAppResponse) GetApp() *WechatApp {
	if x != nil {
		return x.App
	}
	return nil
}

type GetWechatAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWechatAccessTokenRequest) Reset() {
	*x = GetWechatAccessTokenRequest{}
	mi := &file_iam_idp_v2_idp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWechatAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWechatAccessTokenRequest) ProtoMessage() {}

func (x *GetWechatAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_idp_v2_idp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWechatAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*GetWechatAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_iam_idp_v2_idp_proto_rawDescGZIP(), []int{3}
}

func (x *GetWechatAccessTokenRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetWechatAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWechatAccessTokenResponse) Reset() {
	*x = GetWechatAccessTokenResponse{}
	mi := &file_iam_idp_v2_idp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWechatAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWechatAccessTokenResponse) ProtoMessage() {}

func (x *GetWechatAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_idp_v2_idp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWechatAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*GetWechatAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_iam_idp_v2_idp_proto_rawDescGZIP(), []int{4}
}

func (x *GetWechatAccessTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RefreshWechatAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshWechatAccessTokenRequest) Reset() {
	*x = RefreshWechatAccessTokenRequest{}
	mi := &file_iam_idp_v2_idp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshWechatAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshWechatAccessTokenRequest) ProtoMessage() {}

func (x *RefreshWechatAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_idp_v2_idp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshWechatAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshWechatAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_iam_idp_v2_idp_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshWechatAccessTokenRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type RefreshWechatAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshWechatAccessTokenResponse) Reset() {
	*x = RefreshWechatAccessTokenResponse{}
	mi := &file_iam_idp_v2_idp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshWechatAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshWechatAccessTokenResponse) ProtoMessage() {}

func (x *RefreshWechatAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_idp_v2_idp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshWechatAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshWechatAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_iam_idp_v2_idp_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshWechatAccessTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

var File_iam_idp_v2_idp_proto protoreflect.FileDescriptor

const file_iam_idp_v2_idp_proto_rawDesc = "" +
	"\n" +
	"\x14iam/idp/v2/idp.proto\x12\n" +
	"iam.idp.v2\"\xc9\x01\n" +
	"\tWechatApp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x03 \x01(\tR\tappSecret\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\x05 \x01(\x0e2\x19.iam.idp.v2.WechatAppTypeR\x04type\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.iam.idp.v2.WechatAppStatusR\x06status\",\n" +
	"\x13GetWechatAppRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"?\n" +
	"\x14GetWechatAppResponse\x12'\n" +
	"\x03app\x18\x01 \x01(\v2\x15.iam.idp.v2.WechatAppR\x03app\"4\n" +
	"\x1bGetWechatAccessTokenRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"A\n" +
	"\x1cGetWechatAccessTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"8\n" +
	"\x1fRefreshWechatAccessTokenRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"E\n" +
	" RefreshWechatAccessTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken*\x95\x01\n" +
	"\rWechatAppType\x12\x1f\n" +
	"\x1bWECHAT_APP_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cWECHAT_APP_TYPE_MINI_PROGRAM\x10\x01\x12\x16\n" +
	"\x12WECHAT_APP_TYPE_MP\x10\x02\x12)\n" +
	"%WECHAT_APP_TYPE_OPEN_PLATFORM_WEBSITE\x10\x03*\x93\x01\n" +
	"\x0fWechatAppStatus\x12!\n" +
	"\x1dWECHAT_APP_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WECHAT_APP_STATUS_ENABLED\x10\x01\x12\x1e\n" +
	"\x1aWECHAT_APP_STATUS_DISABLED\x10\x02\x12\x1e\n" +
	"\x1aWECHAT_APP_STATUS_ARCHIVED\x10\x032\xc1\x02\n" +
	"\n" +
	"IDPService\x12Q\n" +
	"\fGetWechatApp\x12\x1f.iam.idp.v2.GetWechatAppRequest\x1a .iam.idp.v2.GetWechatAppResponse\x12i\n" +
	"\x14GetWechatAccessToken\x12'.iam.idp.v2.GetWechatAccessTokenRequest\x1a(.iam.idp.v2.GetWechatAccessTokenResponse\x12u\n" +
	"\x18RefreshWechatAccessToken\x12+.iam.idp.v2.RefreshWechatAccessTokenRequest\x1a,.iam.idp.v2.RefreshWechatAccessTokenResponseB:Z8github.com/FangcunMount/iam/v4/api/grpc/iam/idp/v2;idpv2b\x06proto3"

var (
	file_iam_idp_v2_idp_proto_rawDescOnce sync.Once
	file_iam_idp_v2_idp_proto_rawDescData []byte
)

func file_iam_idp_v2_idp_proto_rawDescGZIP() []byte {
	file_iam_idp_v2_idp_proto_rawDescOnce.Do(func() {
		file_iam_idp_v2_idp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_idp_v2_idp_proto_rawDesc), len(file_iam_idp_v2_idp_proto_rawDesc)))
	})
	return file_iam_idp_v2_idp_proto_rawDescData
}

var file_iam_idp_v2_idp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_iam_idp_v2_idp_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_iam_idp_v2_idp_proto_goTypes = []any{
	(WechatAppType)(0),                       // 0: iam.idp.v2.WechatAppType
	(WechatAppStatus)(0),                     // 1: iam.idp.v2.WechatAppStatus
	(*WechatApp)(nil),                        // 2: iam.idp.v2.WechatApp
	(*GetWechatAppRequest)(nil),              // 3: iam.idp.v2.GetWechatAppRequest
	(*GetWechatAppResponse)(nil),             // 4: iam.idp.v2.GetWechatAppResponse
	(*GetWechatAccessTokenRequest)(nil),      // 5: iam.idp.v2.GetWechatAccessTokenRequest
	(*GetWechatAccessTokenResponse)(nil),     // 6: iam.idp.v2.GetWechatAccessTokenResponse
	(*RefreshWechatAccessTokenRequest)(nil),  // 7: iam.idp.v2.RefreshWechatAccessTokenRequest
	(*RefreshWechatAccessTokenResponse)(nil), // 8: iam.idp.v2.RefreshWechatAccessTokenResponse
}
var file_iam_idp_v2_idp_proto_depIdxs = []int32{
	0, // 0: iam.idp.v2.WechatApp.type:type_name -> iam.idp.v2.WechatAppType
	1, // 1: iam.idp.v2.WechatApp.status:type_name -> iam.idp.v2.WechatAppStatus
	2, // 2: iam.idp.v2.GetWechatAppResponse.app:type_name -> iam.idp.v2.WechatApp
	3, // 3: iam.idp.v2.IDPService.GetWechatApp:input_type -> iam.idp.v2.GetWechatAppRequest
	5, // 4: iam.idp.v2.IDPService.GetWechatAccessToken:input_type -> iam.idp.v2.GetWechatAccessTokenRequest
	7, // 5: iam.idp.v2.IDPService.RefreshWechatAccessToken:input_type -> iam.idp.v2.RefreshWechatAccessTokenRequest
	4, // 6: iam.idp.v2.IDPService.GetWechatApp:output_type -> iam.idp.v2.GetWechatAppResponse
	6, // 7: iam.idp.v2.IDPService.GetWechatAccessToken:output_type -> iam.idp.v2.GetWechatAccessTokenResponse
	8, // 8: iam.idp.v2.IDPService.RefreshWechatAccessToken:output_type -> iam.idp.v2.RefreshWechatAccessTokenResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_iam_idp_v2_idp_proto_init() }
func file_iam_idp_v2_idp_proto_init() {
	if File_iam_idp_v2_idp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_idp_v2_idp_proto_rawDesc), len(file_iam_idp_v2_idp_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_idp_v2_idp_proto_goTypes,
		DependencyIndexes: file_iam_idp_v2_idp_proto_depIdxs,
		EnumInfos:         file_iam_idp_v2_idp_proto_enumTypes,
		MessageInfos:      file_iam_idp_v2_idp_proto_msgTypes,
	}.Build()
	File_iam_idp_v2_idp_proto = out.File
	file_iam_idp_v2_idp_proto_goTypes = nil
	file_iam_idp_v2_idp_proto_depIdxs = nil
}
