// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: iam/authz/v1/authz.proto

package authzv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Casbin sub，如 user:<uuid>、group:<id>
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// 租户域，与 Casbin dom 一致
	Domain        string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Object        string `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Action        string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_iam_authz_v1_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v1_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_iam_authz_v1_authz_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CheckRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CheckRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *CheckRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_iam_authz_v1_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authz_v1_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_iam_authz_v1_authz_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_iam_authz_v1_authz_proto protoreflect.FileDescriptor

const file_iam_authz_v1_authz_proto_rawDesc = "" +
	"\n" +
	"\x18iam/authz/v1/authz.proto\x12\fiam.authz.v1\"p\n" +
	"\fCheckRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\")\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed2X\n" +
	"\x14AuthorizationService\x12@\n" +
	"\x05Check\x12\x1a.iam.authz.v1.CheckRequest\x1a\x1b.iam.authz.v1.CheckResponseBEZCgithub.com/FangcunMount/iam-contracts/api/grpc/iam/authz/v1;authzv1b\x06proto3"

var (
	file_iam_authz_v1_authz_proto_rawDescOnce sync.Once
	file_iam_authz_v1_authz_proto_rawDescData []byte
)

func file_iam_authz_v1_authz_proto_rawDescGZIP() []byte {
	file_iam_authz_v1_authz_proto_rawDescOnce.Do(func() {
		file_iam_authz_v1_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_authz_v1_authz_proto_rawDesc), len(file_iam_authz_v1_authz_proto_rawDesc)))
	})
	return file_iam_authz_v1_authz_proto_rawDescData
}

var file_iam_authz_v1_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_iam_authz_v1_authz_proto_goTypes = []any{
	(*CheckRequest)(nil),  // 0: iam.authz.v1.CheckRequest
	(*CheckResponse)(nil), // 1: iam.authz.v1.CheckResponse
}
var file_iam_authz_v1_authz_proto_depIdxs = []int32{
	0, // 0: iam.authz.v1.AuthorizationService.Check:input_type -> iam.authz.v1.CheckRequest
	1, // 1: iam.authz.v1.AuthorizationService.Check:output_type -> iam.authz.v1.CheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_iam_authz_v1_authz_proto_init() }
func file_iam_authz_v1_authz_proto_init() {
	if File_iam_authz_v1_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_authz_v1_authz_proto_rawDesc), len(file_iam_authz_v1_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_authz_v1_authz_proto_goTypes,
		DependencyIndexes: file_iam_authz_v1_authz_proto_depIdxs,
		MessageInfos:      file_iam_authz_v1_authz_proto_msgTypes,
	}.Build()
	File_iam_authz_v1_authz_proto = out.File
	file_iam_authz_v1_authz_proto_goTypes = nil
	file_iam_authz_v1_authz_proto_depIdxs = nil
}
