// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: iam/authn/v1/authn.proto

package authnv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenStatus int32

const (
	TokenStatus_TOKEN_STATUS_UNSPECIFIED TokenStatus = 0
	TokenStatus_TOKEN_STATUS_VALID       TokenStatus = 1
	TokenStatus_TOKEN_STATUS_REVOKED     TokenStatus = 2
	TokenStatus_TOKEN_STATUS_EXPIRED     TokenStatus = 3
)

// Enum value maps for TokenStatus.
var (
	TokenStatus_name = map[int32]string{
		0: "TOKEN_STATUS_UNSPECIFIED",
		1: "TOKEN_STATUS_VALID",
		2: "TOKEN_STATUS_REVOKED",
		3: "TOKEN_STATUS_EXPIRED",
	}
	TokenStatus_value = map[string]int32{
		"TOKEN_STATUS_UNSPECIFIED": 0,
		"TOKEN_STATUS_VALID":       1,
		"TOKEN_STATUS_REVOKED":     2,
		"TOKEN_STATUS_EXPIRED":     3,
	}
)

func (x TokenStatus) Enum() *TokenStatus {
	p := new(TokenStatus)
	*p = x
	return p
}

func (x TokenStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_authn_v1_authn_proto_enumTypes[0].Descriptor()
}

func (TokenStatus) Type() protoreflect.EnumType {
	return &file_iam_authn_v1_authn_proto_enumTypes[0]
}

func (x TokenStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenStatus.Descriptor instead.
func (TokenStatus) EnumDescriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{0}
}

type TokenType int32

const (
	TokenType_TOKEN_TYPE_UNSPECIFIED TokenType = 0
	TokenType_TOKEN_TYPE_ACCESS      TokenType = 1
	TokenType_TOKEN_TYPE_REFRESH     TokenType = 2
	TokenType_TOKEN_TYPE_SERVICE     TokenType = 3
)

// Enum value maps for TokenType.
var (
	TokenType_name = map[int32]string{
		0: "TOKEN_TYPE_UNSPECIFIED",
		1: "TOKEN_TYPE_ACCESS",
		2: "TOKEN_TYPE_REFRESH",
		3: "TOKEN_TYPE_SERVICE",
	}
	TokenType_value = map[string]int32{
		"TOKEN_TYPE_UNSPECIFIED": 0,
		"TOKEN_TYPE_ACCESS":      1,
		"TOKEN_TYPE_REFRESH":     2,
		"TOKEN_TYPE_SERVICE":     3,
	}
)

func (x TokenType) Enum() *TokenType {
	p := new(TokenType)
	*p = x
	return p
}

func (x TokenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenType) Descriptor() protoreflect.EnumDescriptor {
	return file_iam_authn_v1_authn_proto_enumTypes[1].Descriptor()
}

func (TokenType) Type() protoreflect.EnumType {
	return &file_iam_authn_v1_authn_proto_enumTypes[1]
}

func (x TokenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenType.Descriptor instead.
func (TokenType) EnumDescriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{1}
}

type OperatorContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    string                 `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	OperatorName  string                 `protobuf:"bytes,2,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,10,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorContext) Reset() {
	*x = OperatorContext{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorContext) ProtoMessage() {}

func (x *OperatorContext) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorContext.ProtoReflect.Descriptor instead.
func (*OperatorContext) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{0}
}

func (x *OperatorContext) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *OperatorContext) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *OperatorContext) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *OperatorContext) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OperatorContext) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type TokenClaims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Issuer        string                 `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience      []string               `protobuf:"bytes,6,rep,name=audience,proto3" json:"audience,omitempty"`
	TenantId      string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,20,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenClaims) Reset() {
	*x = TokenClaims{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenClaims) ProtoMessage() {}

func (x *TokenClaims) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenClaims.ProtoReflect.Descriptor instead.
func (*TokenClaims) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{1}
}

func (x *TokenClaims) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *TokenClaims) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TokenClaims) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenClaims) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *TokenClaims) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *TokenClaims) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *TokenClaims) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TokenClaims) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *TokenClaims) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TokenClaims) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type TokenPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenType     string                 `protobuf:"bytes,1,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     *durationpb.Duration   `protobuf:"bytes,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{2}
}

func (x *TokenPair) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenPair) GetExpiresIn() *durationpb.Duration {
	if x != nil {
		return x.ExpiresIn
	}
	return nil
}

type TokenMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenType     TokenType              `protobuf:"varint,1,opt,name=token_type,json=tokenType,proto3,enum=iam.authn.v1.TokenType" json:"token_type,omitempty"`
	Status        TokenStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=iam.authn.v1.TokenStatus" json:"status,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenMetadata) Reset() {
	*x = TokenMetadata{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenMetadata) ProtoMessage() {}

func (x *TokenMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenMetadata.ProtoReflect.Descriptor instead.
func (*TokenMetadata) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{3}
}

func (x *TokenMetadata) GetTokenType() TokenType {
	if x != nil {
		return x.TokenType
	}
	return TokenType_TOKEN_TYPE_UNSPECIFIED
}

func (x *TokenMetadata) GetStatus() TokenStatus {
	if x != nil {
		return x.Status
	}
	return TokenStatus_TOKEN_STATUS_UNSPECIFIED
}

func (x *TokenMetadata) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *TokenMetadata) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type VerifyTokenRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ForceRemote     bool                   `protobuf:"varint,2,opt,name=force_remote,json=forceRemote,proto3" json:"force_remote,omitempty"`
	IncludeMetadata bool                   `protobuf:"varint,3,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VerifyTokenRequest) GetForceRemote() bool {
	if x != nil {
		return x.ForceRemote
	}
	return false
}

func (x *VerifyTokenRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Status        TokenStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=iam.authn.v1.TokenStatus" json:"status,omitempty"`
	Claims        *TokenClaims           `protobuf:"bytes,3,opt,name=claims,proto3" json:"claims,omitempty"`
	Metadata      *TokenMetadata         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	FailureReason string                 `protobuf:"bytes,5,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResponse) GetStatus() TokenStatus {
	if x != nil {
		return x.Status
	}
	return TokenStatus_TOKEN_STATUS_UNSPECIFIED
}

func (x *VerifyTokenResponse) GetClaims() *TokenClaims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *VerifyTokenResponse) GetMetadata() *TokenMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VerifyTokenResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Context       map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenPair     *TokenPair             `protobuf:"bytes,1,opt,name=token_pair,json=tokenPair,proto3" json:"token_pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenResponse) GetTokenPair() *TokenPair {
	if x != nil {
		return x.TokenPair
	}
	return nil
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Operator      *OperatorContext       `protobuf:"bytes,10,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RevokeTokenRequest) GetOperator() *OperatorContext {
	if x != nil {
		return x.Operator
	}
	return nil
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{9}
}

type RevokeRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Operator      *OperatorContext       `protobuf:"bytes,10,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRefreshTokenRequest) Reset() {
	*x = RevokeRefreshTokenRequest{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshTokenRequest) ProtoMessage() {}

func (x *RevokeRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RevokeRefreshTokenRequest) GetOperator() *OperatorContext {
	if x != nil {
		return x.Operator
	}
	return nil
}

type RevokeRefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRefreshTokenResponse) Reset() {
	*x = RevokeRefreshTokenResponse{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshTokenResponse) ProtoMessage() {}

func (x *RevokeRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{11}
}

type IssueServiceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Audience      []string               `protobuf:"bytes,2,rep,name=audience,proto3" json:"audience,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Operator      *OperatorContext       `protobuf:"bytes,10,opt,name=operator,proto3" json:"operator,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,20,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueServiceTokenRequest) Reset() {
	*x = IssueServiceTokenRequest{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueServiceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueServiceTokenRequest) ProtoMessage() {}

func (x *IssueServiceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueServiceTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueServiceTokenRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{12}
}

func (x *IssueServiceTokenRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IssueServiceTokenRequest) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *IssueServiceTokenRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *IssueServiceTokenRequest) GetOperator() *OperatorContext {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *IssueServiceTokenRequest) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type IssueServiceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenPair     *TokenPair             `protobuf:"bytes,1,opt,name=token_pair,json=tokenPair,proto3" json:"token_pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueServiceTokenResponse) Reset() {
	*x = IssueServiceTokenResponse{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueServiceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueServiceTokenResponse) ProtoMessage() {}

func (x *IssueServiceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueServiceTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueServiceTokenResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{13}
}

func (x *IssueServiceTokenResponse) GetTokenPair() *TokenPair {
	if x != nil {
		return x.TokenPair
	}
	return nil
}

type GetJWKSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWKSRequest) Reset() {
	*x = GetJWKSRequest{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWKSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWKSRequest) ProtoMessage() {}

func (x *GetJWKSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWKSRequest.ProtoReflect.Descriptor instead.
func (*GetJWKSRequest) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{14}
}

type GetJWKSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwks          []byte                 `protobuf:"bytes,1,opt,name=jwks,proto3" json:"jwks,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	LastModified  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWKSResponse) Reset() {
	*x = GetJWKSResponse{}
	mi := &file_iam_authn_v1_authn_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWKSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWKSResponse) ProtoMessage() {}

func (x *GetJWKSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_authn_v1_authn_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWKSResponse.ProtoReflect.Descriptor instead.
func (*GetJWKSResponse) Descriptor() ([]byte, []int) {
	return file_iam_authn_v1_authn_proto_rawDescGZIP(), []int{15}
}

func (x *GetJWKSResponse) GetJwks() []byte {
	if x != nil {
		return x.Jwks
	}
	return nil
}

func (x *GetJWKSResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *GetJWKSResponse) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

var File_iam_authn_v1_authn_proto protoreflect.FileDescriptor

const file_iam_authn_v1_authn_proto_rawDesc = "" +
	"\n" +
	"\x18iam/authn/v1/authn.proto\x12\fiam.authn.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x02\n" +
	"\x0fOperatorContext\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\tR\n" +
	"operatorId\x12#\n" +
	"\roperator_name\x18\x02 \x01(\tR\foperatorName\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12>\n" +
	"\x05extra\x18\n" +
	" \x03(\v2(.iam.authn.v1.OperatorContext.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x03\n" +
	"\vTokenClaims\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\x12\x16\n" +
	"\x06issuer\x18\x05 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x06 \x03(\tR\baudience\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\x127\n" +
	"\tissued_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12I\n" +
	"\n" +
	"attributes\x18\x14 \x03(\v2).iam.authn.v1.TokenClaims.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\tTokenPair\x12\x1d\n" +
	"\n" +
	"token_type\x18\x01 \x01(\tR\ttokenType\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x128\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\texpiresIn\"\xee\x01\n" +
	"\rTokenMetadata\x126\n" +
	"\n" +
	"token_type\x18\x01 \x01(\x0e2\x17.iam.authn.v1.TokenTypeR\ttokenType\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.iam.authn.v1.TokenStatusR\x06status\x127\n" +
	"\tissued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x85\x01\n" +
	"\x12VerifyTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12!\n" +
	"\fforce_remote\x18\x02 \x01(\bR\vforceRemote\x12)\n" +
	"\x10include_metadata\x18\x03 \x01(\bR\x0fincludeMetadata\"\xf1\x01\n" +
	"\x13VerifyTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.iam.authn.v1.TokenStatusR\x06status\x121\n" +
	"\x06claims\x18\x03 \x01(\v2\x19.iam.authn.v1.TokenClaimsR\x06claims\x127\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1b.iam.authn.v1.TokenMetadataR\bmetadata\x12%\n" +
	"\x0efailure_reason\x18\x05 \x01(\tR\rfailureReason\"\xc0\x01\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12H\n" +
	"\acontext\x18\x02 \x03(\v2..iam.authn.v1.RefreshTokenRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x14RefreshTokenResponse\x126\n" +
	"\n" +
	"token_pair\x18\x01 \x01(\v2\x17.iam.authn.v1.TokenPairR\ttokenPair\"r\n" +
	"\x12RevokeTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x129\n" +
	"\boperator\x18\n" +
	" \x01(\v2\x1d.iam.authn.v1.OperatorContextR\boperator\"\x15\n" +
	"\x13RevokeTokenResponse\"{\n" +
	"\x19RevokeRefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x129\n" +
	"\boperator\x18\n" +
	" \x01(\v2\x1d.iam.authn.v1.OperatorContextR\boperator\"\x1c\n" +
	"\x1aRevokeRefreshTokenResponse\"\xf1\x01\n" +
	"\x18IssueServiceTokenRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\baudience\x18\x02 \x03(\tR\baudience\x12+\n" +
	"\x03ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x129\n" +
	"\boperator\x18\n" +
	" \x01(\v2\x1d.iam.authn.v1.OperatorContextR\boperator\x127\n" +
	"\n" +
	"attributes\x18\x14 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\"S\n" +
	"\x19IssueServiceTokenResponse\x126\n" +
	"\n" +
	"token_pair\x18\x01 \x01(\v2\x17.iam.authn.v1.TokenPairR\ttokenPair\"\x10\n" +
	"\x0eGetJWKSRequest\"z\n" +
	"\x0fGetJWKSResponse\x12\x12\n" +
	"\x04jwks\x18\x01 \x01(\fR\x04jwks\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x12?\n" +
	"\rlast_modified\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified*w\n" +
	"\vTokenStatus\x12\x1c\n" +
	"\x18TOKEN_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TOKEN_STATUS_VALID\x10\x01\x12\x18\n" +
	"\x14TOKEN_STATUS_REVOKED\x10\x02\x12\x18\n" +
	"\x14TOKEN_STATUS_EXPIRED\x10\x03*n\n" +
	"\tTokenType\x12\x1a\n" +
	"\x16TOKEN_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TOKEN_TYPE_ACCESS\x10\x01\x12\x16\n" +
	"\x12TOKEN_TYPE_REFRESH\x10\x02\x12\x16\n" +
	"\x12TOKEN_TYPE_SERVICE\x10\x032\xdb\x03\n" +
	"\vAuthService\x12R\n" +
	"\vVerifyToken\x12 .iam.authn.v1.VerifyTokenRequest\x1a!.iam.authn.v1.VerifyTokenResponse\x12U\n" +
	"\fRefreshToken\x12!.iam.authn.v1.RefreshTokenRequest\x1a\".iam.authn.v1.RefreshTokenResponse\x12R\n" +
	"\vRevokeToken\x12 .iam.authn.v1.RevokeTokenRequest\x1a!.iam.authn.v1.RevokeTokenResponse\x12g\n" +
	"\x12RevokeRefreshToken\x12'.iam.authn.v1.RevokeRefreshTokenRequest\x1a(.iam.authn.v1.RevokeRefreshTokenResponse\x12d\n" +
	"\x11IssueServiceToken\x12&.iam.authn.v1.IssueServiceTokenRequest\x1a'.iam.authn.v1.IssueServiceTokenResponse2U\n" +
	"\vJWKSService\x12F\n" +
	"\aGetJWKS\x12\x1c.iam.authn.v1.GetJWKSRequest\x1a\x1d.iam.authn.v1.GetJWKSResponseBEZCgithub.com/FangcunMount/iam-contracts/api/grpc/iam/authn/v1;authnv1b\x06proto3"

var (
	file_iam_authn_v1_authn_proto_rawDescOnce sync.Once
	file_iam_authn_v1_authn_proto_rawDescData []byte
)

func file_iam_authn_v1_authn_proto_rawDescGZIP() []byte {
	file_iam_authn_v1_authn_proto_rawDescOnce.Do(func() {
		file_iam_authn_v1_authn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_authn_v1_authn_proto_rawDesc), len(file_iam_authn_v1_authn_proto_rawDesc)))
	})
	return file_iam_authn_v1_authn_proto_rawDescData
}

var file_iam_authn_v1_authn_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_iam_authn_v1_authn_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_iam_authn_v1_authn_proto_goTypes = []any{
	(TokenStatus)(0),                   // 0: iam.authn.v1.TokenStatus
	(TokenType)(0),                     // 1: iam.authn.v1.TokenType
	(*OperatorContext)(nil),            // 2: iam.authn.v1.OperatorContext
	(*TokenClaims)(nil),                // 3: iam.authn.v1.TokenClaims
	(*TokenPair)(nil),                  // 4: iam.authn.v1.TokenPair
	(*TokenMetadata)(nil),              // 5: iam.authn.v1.TokenMetadata
	(*VerifyTokenRequest)(nil),         // 6: iam.authn.v1.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),        // 7: iam.authn.v1.VerifyTokenResponse
	(*RefreshTokenRequest)(nil),        // 8: iam.authn.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),       // 9: iam.authn.v1.RefreshTokenResponse
	(*RevokeTokenRequest)(nil),         // 10: iam.authn.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),        // 11: iam.authn.v1.RevokeTokenResponse
	(*RevokeRefreshTokenRequest)(nil),  // 12: iam.authn.v1.RevokeRefreshTokenRequest
	(*RevokeRefreshTokenResponse)(nil), // 13: iam.authn.v1.RevokeRefreshTokenResponse
	(*IssueServiceTokenRequest)(nil),   // 14: iam.authn.v1.IssueServiceTokenRequest
	(*IssueServiceTokenResponse)(nil),  // 15: iam.authn.v1.IssueServiceTokenResponse
	(*GetJWKSRequest)(nil),             // 16: iam.authn.v1.GetJWKSRequest
	(*GetJWKSResponse)(nil),            // 17: iam.authn.v1.GetJWKSResponse
	nil,                                // 18: iam.authn.v1.OperatorContext.ExtraEntry
	nil,                                // 19: iam.authn.v1.TokenClaims.AttributesEntry
	nil,                                // 20: iam.authn.v1.RefreshTokenRequest.ContextEntry
	(*timestamppb.Timestamp)(nil),      // 21: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 22: google.protobuf.Duration
	(*structpb.Struct)(nil),            // 23: google.protobuf.Struct
}
var file_iam_authn_v1_authn_proto_depIdxs = []int32{
	18, // 0: iam.authn.v1.OperatorContext.extra:type_name -> iam.authn.v1.OperatorContext.ExtraEntry
	21, // 1: iam.authn.v1.TokenClaims.issued_at:type_name -> google.protobuf.Timestamp
	21, // 2: iam.authn.v1.TokenClaims.expires_at:type_name -> google.protobuf.Timestamp
	19, // 3: iam.authn.v1.TokenClaims.attributes:type_name -> iam.authn.v1.TokenClaims.AttributesEntry
	22, // 4: iam.authn.v1.TokenPair.expires_in:type_name -> google.protobuf.Duration
	1,  // 5: iam.authn.v1.TokenMetadata.token_type:type_name -> iam.authn.v1.TokenType
	0,  // 6: iam.authn.v1.TokenMetadata.status:type_name -> iam.authn.v1.TokenStatus
	21, // 7: iam.authn.v1.TokenMetadata.issued_at:type_name -> google.protobuf.Timestamp
	21, // 8: iam.authn.v1.TokenMetadata.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 9: iam.authn.v1.VerifyTokenResponse.status:type_name -> iam.authn.v1.TokenStatus
	3,  // 10: iam.authn.v1.VerifyTokenResponse.claims:type_name -> iam.authn.v1.TokenClaims
	5,  // 11: iam.authn.v1.VerifyTokenResponse.metadata:type_name -> iam.authn.v1.TokenMetadata
	20, // 12: iam.authn.v1.RefreshTokenRequest.context:type_name -> iam.authn.v1.RefreshTokenRequest.ContextEntry
	4,  // 13: iam.authn.v1.RefreshTokenResponse.token_pair:type_name -> iam.authn.v1.TokenPair
	2,  // 14: iam.authn.v1.RevokeTokenRequest.operator:type_name -> iam.authn.v1.OperatorContext
	2,  // 15: iam.authn.v1.RevokeRefreshTokenRequest.operator:type_name -> iam.authn.v1.OperatorContext
	22, // 16: iam.authn.v1.IssueServiceTokenRequest.ttl:type_name -> google.protobuf.Duration
	2,  // 17: iam.authn.v1.IssueServiceTokenRequest.operator:type_name -> iam.authn.v1.OperatorContext
	23, // 18: iam.authn.v1.IssueServiceTokenRequest.attributes:type_name -> google.protobuf.Struct
	4,  // 19: iam.authn.v1.IssueServiceTokenResponse.token_pair:type_name -> iam.authn.v1.TokenPair
	21, // 20: iam.authn.v1.GetJWKSResponse.last_modified:type_name -> google.protobuf.Timestamp
	6,  // 21: iam.authn.v1.AuthService.VerifyToken:input_type -> iam.authn.v1.VerifyTokenRequest
	8,  // 22: iam.authn.v1.AuthService.RefreshToken:input_type -> iam.authn.v1.RefreshTokenRequest
	10, // 23: iam.authn.v1.AuthService.RevokeToken:input_type -> iam.authn.v1.RevokeTokenRequest
	12, // 24: iam.authn.v1.AuthService.RevokeRefreshToken:input_type -> iam.authn.v1.RevokeRefreshTokenRequest
	14, // 25: iam.authn.v1.AuthService.IssueServiceToken:input_type -> iam.authn.v1.IssueServiceTokenRequest
	16, // 26: iam.authn.v1.JWKSService.GetJWKS:input_type -> iam.authn.v1.GetJWKSRequest
	7,  // 27: iam.authn.v1.AuthService.VerifyToken:output_type -> iam.authn.v1.VerifyTokenResponse
	9,  // 28: iam.authn.v1.AuthService.RefreshToken:output_type -> iam.authn.v1.RefreshTokenResponse
	11, // 29: iam.authn.v1.AuthService.RevokeToken:output_type -> iam.authn.v1.RevokeTokenResponse
	13, // 30: iam.authn.v1.AuthService.RevokeRefreshToken:output_type -> iam.authn.v1.RevokeRefreshTokenResponse
	15, // 31: iam.authn.v1.AuthService.IssueServiceToken:output_type -> iam.authn.v1.IssueServiceTokenResponse
	17, // 32: iam.authn.v1.JWKSService.GetJWKS:output_type -> iam.authn.v1.GetJWKSResponse
	27, // [27:33] is the sub-list for method output_type
	21, // [21:27] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_iam_authn_v1_authn_proto_init() }
func file_iam_authn_v1_authn_proto_init() {
	if File_iam_authn_v1_authn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_authn_v1_authn_proto_rawDesc), len(file_iam_authn_v1_authn_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_iam_authn_v1_authn_proto_goTypes,
		DependencyIndexes: file_iam_authn_v1_authn_proto_depIdxs,
		EnumInfos:         file_iam_authn_v1_authn_proto_enumTypes,
		MessageInfos:      file_iam_authn_v1_authn_proto_msgTypes,
	}.Build()
	File_iam_authn_v1_authn_proto = out.File
	file_iam_authn_v1_authn_proto_goTypes = nil
	file_iam_authn_v1_authn_proto_depIdxs = nil
}
