name: Ping Runner

# Required Secrets: PRODUCTION_HOST, PRODUCTION_USERNAME, PRODUCTION_SSH_KEY, PRODUCTION_SSH_PORT

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  ping-production:
    name: Check Production Server A
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: SSH Health Check
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: ${{ secrets.PRODUCTION_SSH_PORT || 22 }}
          script: |
            echo "=== Production Server A Health Check ==="
            echo "Hostname: $(hostname)"
            echo "Uptime: $(uptime)"
            echo ""
            echo "Memory:"
            free -h | grep -E "Mem|Swap"
            echo ""
            echo "Disk:"
            df -h | grep -E "^/dev/"
            echo ""
            echo "CPU:"
            top -bn1 | grep "Cpu(s)"
            
      - name: Check IAM Service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: ${{ secrets.PRODUCTION_SSH_PORT || 22 }}
          script: |
            if systemctl is-active --quiet iam-apiserver; then
              echo "✅ IAM service is running"
              systemctl status iam-apiserver --no-pager | head -20
            else
              echo "❌ IAM service is not running"
              exit 1
            fi

  ping-github:
    name: Check GitHub Runner
    runs-on: ubuntu-latest
    steps:
      - name: Runner Info
        run: |
          echo "=== GitHub Runner Info ==="
          echo "OS: ${{ runner.os }}"
          echo "Name: ${{ runner.name }}"
          echo "Arch: ${{ runner.arch }}"
          echo "✅ Runner OK"

  report:
    name: Status Report
    needs: [ping-production, ping-github]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Report
        run: |
          echo "=== Status Report ==="
          echo "Production: ${{ needs.ping-production.result }}"
          echo "GitHub: ${{ needs.ping-github.result }}"
          
          if [ "${{ needs.ping-production.result }}" != "success" ]; then
            echo "⚠️ Production check failed!"
            exit 1
          fi
          
          echo "✅ All OK"
