// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: qs_bootstrap.proto

package qsbootstrappb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootstrapOperatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         int64                  `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapOperatorRequest) Reset() {
	*x = BootstrapOperatorRequest{}
	mi := &file_qs_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapOperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapOperatorRequest) ProtoMessage() {}

func (x *BootstrapOperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qs_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapOperatorRequest.ProtoReflect.Descriptor instead.
func (*BootstrapOperatorRequest) Descriptor() ([]byte, []int) {
	return file_qs_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *BootstrapOperatorRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *BootstrapOperatorRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BootstrapOperatorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BootstrapOperatorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BootstrapOperatorRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *BootstrapOperatorRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type BootstrapOperatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    uint64                 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapOperatorResponse) Reset() {
	*x = BootstrapOperatorResponse{}
	mi := &file_qs_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapOperatorResponse) ProtoMessage() {}

func (x *BootstrapOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qs_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapOperatorResponse.ProtoReflect.Descriptor instead.
func (*BootstrapOperatorResponse) Descriptor() ([]byte, []int) {
	return file_qs_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapOperatorResponse) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *BootstrapOperatorResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *BootstrapOperatorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BootstrapOperatorResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_qs_bootstrap_proto protoreflect.FileDescriptor

const file_qs_bootstrap_proto_rawDesc = "" +
	"\n" +
	"\x12qs_bootstrap.proto\x12\vinternalapi\"\xa7\x01\n" +
	"\x18BootstrapOperatorRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x03R\x05orgId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"\x86\x01\n" +
	"\x19BootstrapOperatorResponse\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x04R\n" +
	"operatorId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles2u\n" +
	"\x0fInternalService\x12b\n" +
	"\x11BootstrapOperator\x12%.internalapi.BootstrapOperatorRequest\x1a&.internalapi.BootstrapOperatorResponseB_Z]github.com/FangcunMount/iam-contracts/cmd/tools/seeddata/internal/qsbootstrappb;qsbootstrappbb\x06proto3"

var (
	file_qs_bootstrap_proto_rawDescOnce sync.Once
	file_qs_bootstrap_proto_rawDescData []byte
)

func file_qs_bootstrap_proto_rawDescGZIP() []byte {
	file_qs_bootstrap_proto_rawDescOnce.Do(func() {
		file_qs_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qs_bootstrap_proto_rawDesc), len(file_qs_bootstrap_proto_rawDesc)))
	})
	return file_qs_bootstrap_proto_rawDescData
}

var file_qs_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_qs_bootstrap_proto_goTypes = []any{
	(*BootstrapOperatorRequest)(nil),  // 0: internalapi.BootstrapOperatorRequest
	(*BootstrapOperatorResponse)(nil), // 1: internalapi.BootstrapOperatorResponse
}
var file_qs_bootstrap_proto_depIdxs = []int32{
	0, // 0: internalapi.InternalService.BootstrapOperator:input_type -> internalapi.BootstrapOperatorRequest
	1, // 1: internalapi.InternalService.BootstrapOperator:output_type -> internalapi.BootstrapOperatorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qs_bootstrap_proto_init() }
func file_qs_bootstrap_proto_init() {
	if File_qs_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qs_bootstrap_proto_rawDesc), len(file_qs_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qs_bootstrap_proto_goTypes,
		DependencyIndexes: file_qs_bootstrap_proto_depIdxs,
		MessageInfos:      file_qs_bootstrap_proto_msgTypes,
	}.Build()
	File_qs_bootstrap_proto = out.File
	file_qs_bootstrap_proto_goTypes = nil
	file_qs_bootstrap_proto_depIdxs = nil
}
